# Format: (word, turkish, image_prompt, level, category, frequency_rank)

WORDS_DATA = [
    # ─── A1 – Animals ───
    ("cat", "kedi", "A small furry animal with whiskers and a long tail, often curled up sleeping or chasing a ball of yarn", "A1", "animals", 1),
    ("dog", "köpek", "A loyal four-legged animal with floppy ears and a wagging tail, running through a green park", "A1", "animals", 2),
    ("bird", "kuş", "A feathered creature with wings perched on a branch, opening its beak to sing a melody", "A1", "animals", 3),
    ("fish", "balık", "A shiny scaled creature swimming gracefully through clear blue water, blowing tiny bubbles", "A1", "animals", 4),
    ("horse", "at", "A large powerful animal with a flowing mane galloping across an open meadow", "A1", "animals", 5),
    ("cow", "inek", "A large black-and-white spotted animal standing in a green field, being milked by a farmer", "A1", "animals", 6),
    ("pig", "domuz", "A plump pink animal with a curly tail rolling happily in a muddy puddle on a farm", "A1", "animals", 7),
    ("sheep", "koyun", "A fluffy white woolly animal grazing peacefully on a hillside covered in green grass", "A1", "animals", 8),
    ("duck", "ördek", "A plump bird with a flat orange beak waddling beside a pond and splashing in the water", "A1", "animals", 9),
    ("rabbit", "tavşan", "A small fluffy creature with long ears and a cotton tail nibbling on a carrot", "A1", "animals", 10),
    ("bear", "ayı", "A large furry animal with a round face and big paws walking through a dense forest", "A1", "animals", 11),
    ("lion", "aslan", "A majestic big cat with a golden mane resting on a rock in the savanna", "A1", "animals", 12),
    ("tiger", "kaplan", "A striped orange and black big cat crouching low in tall jungle grass", "A1", "animals", 13),
    ("elephant", "fil", "An enormous grey animal with a long trunk, large ears and tusks walking slowly across the plains", "A1", "animals", 14),
    ("monkey", "maymun", "A small agile animal with a long tail swinging from branch to branch high in a tropical tree", "A1", "animals", 15),
    ("snake", "yılan", "A long slender reptile without legs gliding silently through dry leaves on the forest floor", "A1", "animals", 16),
    ("frog", "kurbağa", "A small green amphibian with bulging eyes sitting on a lily pad and leaping into a pond", "A1", "animals", 17),
    ("butterfly", "kelebek", "A delicate winged insect with colorful patterned wings resting on a bright flower", "A1", "animals", 18),
    ("ant", "karınca", "A tiny six-legged insect marching in a long line across a picnic blanket carrying food", "A1", "animals", 19),
    ("bee", "arı", "A yellow and black striped flying insect hovering over flowers collecting nectar", "A1", "animals", 20),

    # ─── A1 – Colors ───
    ("red", "kırmızı", "The bright fiery color of a ripe tomato, a fire truck, and a Valentine's heart", "A1", "colors", 21),
    ("blue", "mavi", "The calming color of a clear sky on a sunny day and the deep ocean water", "A1", "colors", 22),
    ("green", "yeşil", "The fresh vibrant color of new leaves, grass, and the forest in springtime", "A1", "colors", 23),
    ("yellow", "sarı", "The cheerful bright color of sunflowers, ripe bananas, and the midday sun", "A1", "colors", 24),
    ("orange", "turuncu", "The warm vivid color of autumn leaves, ripe citrus fruit, and a glowing sunset", "A1", "colors", 25),
    ("purple", "mor", "The rich royal color of lavender flowers, grapes, and royal robes", "A1", "colors", 26),
    ("white", "beyaz", "The pure clean color of fresh snow, a blank sheet of paper, and fluffy clouds", "A1", "colors", 27),
    ("black", "siyah", "The deep dark color of the night sky, coal, and a sleek luxury car", "A1", "colors", 28),
    ("brown", "kahverengi", "The earthy warm color of tree bark, freshly brewed coffee, and chocolate", "A1", "colors", 29),
    ("pink", "pembe", "The soft delicate color of rose petals, cherry blossoms, and flamingo feathers", "A1", "colors", 30),

    # ─── A1 – Family ───
    ("mother", "anne", "A caring woman hugging her child tightly with a warm loving smile in a cozy home", "A1", "family", 31),
    ("father", "baba", "A man lifting his laughing child onto his shoulders in a sunny backyard", "A1", "family", 32),
    ("sister", "kız kardeş", "Two girls sharing a book together, one older pointing at the pages to help the younger one read", "A1", "family", 33),
    ("brother", "erkek kardeş", "Two boys playing catch in the garden, laughing and running around together", "A1", "family", 34),
    ("baby", "bebek", "A tiny chubby infant wrapped in a soft blanket sleeping peacefully in a crib", "A1", "family", 35),
    ("grandmother", "büyükanne", "An elderly woman with silver hair knitting in a rocking chair by a warm fireplace", "A1", "family", 36),
    ("grandfather", "büyükbaba", "An old man with glasses sitting in a garden telling stories to grandchildren gathered around him", "A1", "family", 37),
    ("family", "aile", "A group of parents and children sitting together at a dining table sharing a meal and laughing", "A1", "family", 38),

    # ─── A1 – Body ───
    ("head", "baş", "The top round part of the body where the face, eyes, and brain are located", "A1", "body", 39),
    ("hand", "el", "Five fingers attached to a palm, used for grasping, writing, and waving hello", "A1", "body", 40),
    ("foot", "ayak", "The lower end of the leg with five toes used for standing, walking, and kicking a ball", "A1", "body", 41),
    ("eye", "göz", "A round organ on the face used for seeing, framed by eyelashes and eyebrows", "A1", "body", 42),
    ("ear", "kulak", "A curved organ on the side of the head used for hearing sounds and music", "A1", "body", 43),
    ("nose", "burun", "The pointed organ in the center of the face used for breathing and smelling flowers", "A1", "body", 44),
    ("mouth", "ağız", "The opening on the face with lips and teeth used for speaking, eating, and smiling", "A1", "body", 45),
    ("hair", "saç", "The strands growing from the top of the head that can be cut, styled, and colored", "A1", "body", 46),
    ("arm", "kol", "The long limb connecting the shoulder to the hand used for reaching and carrying", "A1", "body", 47),
    ("leg", "bacak", "The long limb connecting the hip to the foot used for walking, running, and jumping", "A1", "body", 48),

    # ─── A1 – Food & Drink ───
    ("apple", "elma", "A round smooth fruit that is red or green, sweet or tangy, often eaten as a healthy snack", "A1", "food", 49),
    ("bread", "ekmek", "A baked food made from flour and yeast, golden-brown outside and soft inside, sliced for sandwiches", "A1", "food", 50),
    ("milk", "süt", "A white creamy liquid from cows poured into a glass or used to make cheese and butter", "A1", "food", 51),
    ("water", "su", "A clear colorless liquid essential for life, poured into a glass or flowing from a tap", "A1", "food", 52),
    ("egg", "yumurta", "An oval shell containing a yolk and white, cracked into a pan and fried for breakfast", "A1", "food", 53),
    ("rice", "pirinç", "Small white grains cooked in boiling water and served in a bowl as a staple meal", "A1", "food", 54),
    ("cake", "kek", "A sweet baked dessert decorated with colorful frosting and candles for a birthday celebration", "A1", "food", 55),
    ("soup", "çorba", "A hot liquid dish with vegetables and sometimes meat served in a bowl with a spoon", "A1", "food", 56),
    ("cheese", "peynir", "A dairy product made from milk, yellow or white in color, sliced and placed on a cracker", "A1", "food", 57),
    ("coffee", "kahve", "A dark aromatic hot drink made from ground roasted beans, poured steaming into a white cup", "A1", "food", 58),
    ("tea", "çay", "A warm drink made by steeping dried leaves in hot water, served in a cup with a saucer", "A1", "food", 59),
    ("pizza", "pizza", "A round flat bread topped with tomato sauce, melted cheese, and colorful toppings baked in an oven", "A1", "food", 60),

    # ─── A1 – Clothing ───
    ("shirt", "gömlek", "A garment worn on the upper body with a collar, buttons down the front, and long or short sleeves", "A1", "clothing", 61),
    ("shoes", "ayakkabı", "A pair of foot coverings with soles and laces placed neatly on the floor", "A1", "clothing", 62),
    ("hat", "şapka", "A head covering with a brim that protects from sun or rain, placed on top of the head", "A1", "clothing", 63),
    ("dress", "elbise", "A one-piece garment worn by women and girls that covers from shoulders to below the knees", "A1", "clothing", 64),
    ("coat", "palto", "A long warm outer garment worn over other clothes in cold or rainy weather", "A1", "clothing", 65),
    ("bag", "çanta", "A container with handles used for carrying belongings to school, work, or the market", "A1", "clothing", 66),
    ("glasses", "gözlük", "A frame with two lenses worn on the face to help someone see more clearly", "A1", "clothing", 67),

    # ─── A1 – House ───
    ("house", "ev", "A building with walls, windows, a roof and a door where a family lives together", "A1", "house", 68),
    ("door", "kapı", "A hinged panel in a wall that opens and closes to let people enter or leave a room", "A1", "house", 69),
    ("window", "pencere", "A glass-covered opening in a wall letting light in and offering a view of the outside", "A1", "house", 70),
    ("table", "masa", "A flat horizontal surface supported by four legs where people eat meals or work", "A1", "house", 71),
    ("chair", "sandalye", "A seat with a back support and four legs where a person sits to eat, study or rest", "A1", "house", 72),
    ("bed", "yatak", "A piece of furniture with a soft mattress and pillows where people sleep at night", "A1", "house", 73),
    ("kitchen", "mutfak", "A room with a stove, oven, sink and refrigerator where meals are cooked and prepared", "A1", "house", 74),
    ("bathroom", "banyo", "A room containing a bathtub or shower, sink and toilet used for personal hygiene", "A1", "house", 75),
    ("book", "kitap", "Stacks of pages with text and pictures bound together with a cover, resting on a shelf", "A1", "house", 76),
    ("clock", "saat", "A round device with two hands pointing to numbers displayed on a wall to show the time", "A1", "house", 77),

    # ─── A1 – Nature ───
    ("sun", "güneş", "A bright glowing sphere of light high in the blue sky warming the Earth on a clear day", "A1", "nature", 78),
    ("moon", "ay", "A glowing silver circle visible in the dark night sky surrounded by stars", "A1", "nature", 79),
    ("star", "yıldız", "A tiny bright light twinkling in the black night sky, part of a constellation pattern", "A1", "nature", 80),
    ("rain", "yağmur", "Water droplets falling from grey clouds in the sky, making puddles on the pavement", "A1", "nature", 81),
    ("snow", "kar", "White fluffy frozen water crystals falling from the sky and covering the ground in a white blanket", "A1", "nature", 82),
    ("flower", "çiçek", "A colorful bloom with soft petals opening toward the sun, filling the air with sweet fragrance", "A1", "nature", 83),
    ("tree", "ağaç", "A tall plant with a thick trunk, spreading branches, and green leaves reaching toward the sky", "A1", "nature", 84),
    ("grass", "çimen", "Short green blades of plant covering the ground in a park where children play and picnic", "A1", "nature", 85),
    ("mountain", "dağ", "A massive rocky peak rising high into the clouds with snow capping its summit", "A1", "nature", 86),
    ("sea", "deniz", "A vast expanse of deep blue saltwater stretching to the horizon with waves crashing on the shore", "A1", "nature", 87),
    ("river", "nehir", "A long flowing body of fresh water winding through valleys and forests toward the ocean", "A1", "nature", 88),
    ("sky", "gökyüzü", "The vast blue canopy above the Earth with white clouds drifting and birds soaring", "A1", "nature", 89),

    # ─── A1 – Transport ───
    ("car", "araba", "A four-wheeled vehicle with an engine used to drive people from place to place on roads", "A1", "transport", 90),
    ("bus", "otobüs", "A large vehicle with rows of seats carrying many passengers along a fixed route through the city", "A1", "transport", 91),
    ("train", "tren", "A long vehicle with multiple carriages running on metal rails through cities and countryside", "A1", "transport", 92),
    ("boat", "tekne", "A small water vessel with a hull floating on a river or lake, moved by oars or a motor", "A1", "transport", 93),
    ("plane", "uçak", "A large winged aircraft that carries passengers through the sky between distant cities", "A1", "transport", 94),
    ("bike", "bisiklet", "A two-wheeled vehicle with pedals and handlebars that a person rides by pedaling", "A1", "transport", 95),

    # ─── A1 – Common Verbs ───
    ("run", "koşmak", "A person moving quickly on their feet with both legs lifting off the ground alternately", "A1", "verbs", 96),
    ("jump", "atlamak", "A person bending their knees and springing up into the air off the ground", "A1", "verbs", 97),
    ("swim", "yüzmek", "A person moving through water by moving their arms and kicking their legs", "A1", "verbs", 98),
    ("eat", "yemek", "A person sitting at a table bringing food to their mouth with a fork and chewing", "A1", "verbs", 99),
    ("drink", "içmek", "A person raising a glass to their lips and swallowing a liquid", "A1", "verbs", 100),
    ("sleep", "uyumak", "A person lying in bed with closed eyes, a pillow under their head, in a quiet dark room", "A1", "verbs", 101),
    ("walk", "yürümek", "A person moving forward on two feet at a steady pace along a sidewalk", "A1", "verbs", 102),
    ("read", "okumak", "A person sitting in a chair holding an open book and looking carefully at the words on the page", "A1", "verbs", 103),
    ("write", "yazmak", "A hand holding a pen and moving it across a sheet of paper making letters and words", "A1", "verbs", 104),
    ("play", "oynamak", "Children laughing and running around on a colorful playground with swings and slides", "A1", "verbs", 105),
    ("dance", "dans etmek", "A person moving their body rhythmically to music with arms extended and feet moving", "A1", "verbs", 106),
    ("sing", "şarkı söylemek", "A person standing at a microphone with mouth open and eyes closed, performing a song", "A1", "verbs", 107),
    ("cook", "pişirmek", "A person in an apron standing at a stove stirring a pot with steam rising from it", "A1", "verbs", 108),
    ("open", "açmak", "Two hands gripping the handle of a closed door and pulling it wide open", "A1", "verbs", 109),
    ("close", "kapatmak", "A hand reaching out and pushing a door shut until it clicks into the frame", "A1", "verbs", 110),

    # ─── A1 – Common Adjectives ───
    ("big", "büyük", "An enormous elephant standing next to a tiny mouse to show the difference in size", "A1", "adjectives", 111),
    ("small", "küçük", "A tiny kitten fitting inside a teacup to show how little it is", "A1", "adjectives", 112),
    ("tall", "uzun boylu", "A basketball player stretching to reach a very high shelf that shorter people cannot reach", "A1", "adjectives", 113),
    ("short", "kısa boylu", "A child standing on tiptoes next to a very tall adult trying to reach the same height", "A1", "adjectives", 114),
    ("hot", "sıcak", "Steam rising from a bowl of soup placed on a table showing the heat inside", "A1", "adjectives", 115),
    ("cold", "soğuk", "A glass of water with ice cubes and frost forming on the outside surface", "A1", "adjectives", 116),
    ("fast", "hızlı", "A racing car with motion blur zooming along a track at incredible speed", "A1", "adjectives", 117),
    ("slow", "yavaş", "A tortoise taking careful deliberate steps along a path, moving unhurriedly", "A1", "adjectives", 118),
    ("happy", "mutlu", "A person with a wide smile, bright eyes, and arms raised in a joyful expression", "A1", "adjectives", 119),
    ("sad", "üzgün", "A person sitting alone with drooping shoulders, looking down with a sorrowful expression", "A1", "adjectives", 120),
    ("new", "yeni", "A shiny unopened product still in its original packaging with a price tag attached", "A1", "adjectives", 121),
    ("old", "eski", "A worn-out leather shoe with cracked soles and faded color showing years of use", "A1", "adjectives", 122),
    ("beautiful", "güzel", "A stunning sunset with pink and orange colors reflecting on a calm lake surface", "A1", "adjectives", 123),
    ("clean", "temiz", "A sparkling white plate just washed and dripping with water on a dish rack", "A1", "adjectives", 124),
    ("dirty", "kirli", "Muddy boots with caked soil and stains left at the entrance of a clean house", "A1", "adjectives", 125),

    # ─── A1 – Time ───
    ("morning", "sabah", "Golden sunlight streaming through curtains, a coffee mug steaming, a new day beginning", "A1", "time", 126),
    ("night", "gece", "A dark sky filled with stars and a glowing moon above a quiet sleeping city", "A1", "time", 127),
    ("today", "bugün", "A calendar page circled in red with the current date highlighted", "A1", "time", 128),
    ("week", "hafta", "A calendar showing seven days from Monday to Sunday with each day labeled", "A1", "time", 129),
    ("year", "yıl", "A page from a calendar showing all twelve months of the year arranged in a grid", "A1", "time", 130),

    # ─── A2 – Animals ───
    ("wolf", "kurt", "A grey furry wild animal with yellow eyes howling at the moon in a snowy forest", "A2", "animals", 131),
    ("fox", "tilki", "A clever-looking red and white animal with a bushy tail sneaking through autumn leaves", "A2", "animals", 132),
    ("deer", "geyik", "A graceful animal with spotted coat and branching antlers stepping quietly through the forest", "A2", "animals", 133),
    ("owl", "baykuş", "A round-faced nocturnal bird with large yellow eyes perched silently on a branch at night", "A2", "animals", 134),
    ("parrot", "papağan", "A brightly colored tropical bird with a curved beak sitting on a wooden perch and mimicking words", "A2", "animals", 135),
    ("crocodile", "timsah", "A large reptile with a long jaw full of sharp teeth lying very still at the edge of a river", "A2", "animals", 136),
    ("penguin", "penguen", "A black and white flightless bird waddling on ice in a frozen Antarctic landscape", "A2", "animals", 137),
    ("whale", "balina", "The largest creature on Earth breaching from the ocean and splashing back down into the waves", "A2", "animals", 138),
    ("shark", "köpekbalığı", "A powerful grey fish with a tall dorsal fin cutting through the ocean surface", "A2", "animals", 139),
    ("dolphin", "yunus", "A sleek intelligent marine mammal leaping gracefully above the ocean waves", "A2", "animals", 140),
    ("eagle", "kartal", "A large bird of prey with a hooked beak and powerful wings soaring high above a canyon", "A2", "animals", 141),
    ("camel", "deve", "A large desert animal with a hump on its back walking slowly across golden sand dunes", "A2", "animals", 142),
    ("giraffe", "zürafa", "The world's tallest animal with a long spotted neck stretching up to eat leaves from a treetop", "A2", "animals", 143),

    # ─── A2 – Food ───
    ("banana", "muz", "A curved yellow fruit with a soft creamy interior, peeled and eaten as a sweet snack", "A2", "food", 144),
    ("orange", "portakal", "A round citrus fruit with a bumpy orange skin and juicy sweet flesh divided into segments", "A2", "food", 145),
    ("strawberry", "çilek", "A small red heart-shaped fruit with tiny seeds on its surface dipped in cream or chocolate", "A2", "food", 146),
    ("chocolate", "çikolata", "A rich dark sweet treat made from cocoa, wrapped in foil and broken into squares", "A2", "food", 147),
    ("hamburger", "hamburger", "A round beef patty with lettuce, tomato and cheese between two sesame seed buns", "A2", "food", 148),
    ("sandwich", "sandviç", "Two slices of bread with various fillings like cheese, ham and vegetables pressed together", "A2", "food", 149),
    ("grape", "üzüm", "Small round fruits growing in clusters on a vine, green or purple, sweet and juicy", "A2", "food", 150),
    ("watermelon", "karpuz", "A large round green fruit with bright red juicy flesh filled with black seeds, eaten in slices", "A2", "food", 151),
    ("lemon", "limon", "A bright yellow oval citrus fruit with very sour juice used to flavor food and drinks", "A2", "food", 152),
    ("potato", "patates", "A starchy underground vegetable with brown skin, peeled and boiled, mashed or fried", "A2", "food", 153),
    ("tomato", "domates", "A plump round red fruit used as a vegetable in salads and sauces, sliced on a cutting board", "A2", "food", 154),
    ("pasta", "makarna", "Long thin noodles boiled in water and served with tomato sauce and cheese on a plate", "A2", "food", 155),
    ("salad", "salata", "A bowl of mixed green leaves, tomatoes, cucumbers and other fresh vegetables tossed together", "A2", "food", 156),
    ("garlic", "sarımsak", "A pungent white bulb divided into cloves used to add strong flavor to cooked dishes", "A2", "food", 157),
    ("onion", "soğan", "A round layered vegetable with a papery skin that releases a sharp smell when peeled and cut", "A2", "food", 158),
    ("honey", "bal", "A thick golden liquid made by bees from flower nectar, drizzled from a jar onto toast", "A2", "food", 159),
    ("butter", "tereyağı", "A pale yellow creamy solid made from churned cream, spread onto warm bread with a knife", "A2", "food", 160),
    ("yogurt", "yoğurt", "A thick white creamy dairy product made by fermenting milk, served in a bowl with fresh fruit", "A2", "food", 161),

    # ─── A2 – Places ───
    ("school", "okul", "A large building with many classrooms where children sit at desks and learn from teachers", "A2", "places", 162),
    ("hospital", "hastane", "A large medical building with doctors and nurses caring for patients in white rooms", "A2", "places", 163),
    ("library", "kütüphane", "A quiet building lined with tall shelves of books where people sit and read in silence", "A2", "places", 164),
    ("market", "pazar", "An outdoor area with colourful stalls selling fresh vegetables, fruit and local products", "A2", "places", 165),
    ("restaurant", "restoran", "A place with tables set with napkins and cutlery where people order and eat prepared meals", "A2", "places", 166),
    ("hotel", "otel", "A building with many numbered rooms where travellers stay overnight in comfortable beds", "A2", "places", 167),
    ("park", "park", "An open green space with benches, trees and pathways where people walk and children play", "A2", "places", 168),
    ("beach", "plaj", "A sandy shoreline beside the sea with waves rolling in and people sunbathing under umbrellas", "A2", "places", 169),
    ("airport", "havalimanı", "A large terminal building with departure boards where planes take off and land on long runways", "A2", "places", 170),
    ("museum", "müze", "A building with large halls displaying ancient artefacts and paintings behind glass cases", "A2", "places", 171),
    ("supermarket", "süpermarket", "A large store with aisles of shelves stacked with packaged food and household goods", "A2", "places", 172),
    ("pharmacy", "eczane", "A shop with shelves of medicines and vitamins where a pharmacist fills prescriptions", "A2", "places", 173),

    # ─── A2 – Weather ───
    ("sunny", "güneşli", "A bright blue sky without a single cloud with golden sunlight warming the landscape below", "A2", "weather", 174),
    ("rainy", "yağmurlu", "Dark grey clouds releasing a steady downpour of rain onto wet streets and umbrellas", "A2", "weather", 175),
    ("cloudy", "bulutlu", "A white and grey overcast sky with thick clouds blocking the sun on a mild day", "A2", "weather", 176),
    ("windy", "rüzgarlı", "Tree branches bending dramatically, leaves swirling through the air, hair blowing sideways", "A2", "weather", 177),
    ("foggy", "sisli", "A landscape where buildings and trees fade into a thick white mist reducing visibility", "A2", "weather", 178),
    ("stormy", "fırtınalı", "Dark towering clouds with lightning bolts striking and heavy rain lashing a seascape", "A2", "weather", 179),
    ("freezing", "dondurucu", "A thermometer showing well below zero with icicles hanging from rooftops and frozen ponds", "A2", "weather", 180),
    ("warm", "ilık", "People relaxing outside in light clothing enjoying comfortable mild sunshine in a garden", "A2", "weather", 181),
    ("humid", "nemli", "A tropical landscape with heat shimmer rising from the ground and people sweating in sticky air", "A2", "weather", 182),

    # ─── A2 – Emotions ───
    ("angry", "kızgın", "A person with a furrowed brow, reddened face and clenched fists in a heated argument", "A2", "emotions", 183),
    ("excited", "heyecanlı", "A person jumping up and down with wide eyes and arms raised in thrilled anticipation", "A2", "emotions", 184),
    ("surprised", "şaşırmış", "A person with mouth wide open, eyebrows raised high, and eyes wide at an unexpected moment", "A2", "emotions", 185),
    ("bored", "sıkılmış", "A person slumped in a chair, staring blankly at the ceiling with a heavy sigh", "A2", "emotions", 186),
    ("tired", "yorgun", "A person with drooping eyelids, slumped posture, yawning widely after a long day of work", "A2", "emotions", 187),
    ("afraid", "korkmuş", "A person with wide frightened eyes hiding behind a door in a dark hallway", "A2", "emotions", 188),
    ("proud", "gururlu", "A person standing upright with a big smile holding a trophy or medal, chest puffed out", "A2", "emotions", 189),
    ("lonely", "yalnız", "A single person sitting on a park bench far from others, watching people pass by", "A2", "emotions", 190),
    ("worried", "endişeli", "A person biting their nails and pacing back and forth looking at their phone anxiously", "A2", "emotions", 191),
    ("calm", "sakin", "A person sitting cross-legged in a peaceful garden with eyes closed, breathing slowly", "A2", "emotions", 192),

    # ─── A2 – Household ───
    ("cup", "kupa/fincan", "A ceramic container with a handle filled with hot tea or coffee resting on a saucer", "A2", "household", 193),
    ("plate", "tabak", "A round flat white dish holding a meal at a dining table set with cutlery", "A2", "household", 194),
    ("knife", "bıçak", "A metal utensil with a sharp blade used for cutting food on a chopping board", "A2", "household", 195),
    ("spoon", "kaşık", "A small oval bowl on a handle used for stirring soup and scooping soft foods", "A2", "household", 196),
    ("lamp", "lamba", "A light fixture on a bedside table casting a warm yellow glow in a dim room", "A2", "household", 197),
    ("mirror", "ayna", "A glass surface that reflects a clear image of the person standing in front of it", "A2", "household", 198),
    ("sofa", "kanepe", "A large padded seat with armrests and a back where several people sit comfortably together", "A2", "household", 199),
    ("carpet", "halı", "A soft patterned fabric covering a floor in a living room, warm underfoot", "A2", "household", 200),
    ("key", "anahtar", "A small metal object with ridges that fits into a lock to open a door", "A2", "household", 201),
    ("towel", "havlu", "A thick absorbent piece of cloth used to dry the body after bathing, hanging on a rack", "A2", "household", 202),
    ("pillow", "yastık", "A soft rectangular cushion stuffed with filling placed under the head on a bed for sleep", "A2", "household", 203),
    ("umbrella", "şemsiye", "A portable canopy on a metal frame opened above a person's head to protect from rain", "A2", "household", 204),

    # ─── A2 – Common Verbs ───
    ("buy", "satın almak", "A person at a shop counter handing over money to a cashier in exchange for a product", "A2", "verbs", 205),
    ("sell", "satmak", "A market vendor handing over a bag of goods to a customer who pays at a stall", "A2", "verbs", 206),
    ("travel", "seyahat etmek", "A person with a suitcase at an airport looking up at a departures board with excitement", "A2", "verbs", 207),
    ("learn", "öğrenmek", "A student sitting at a desk with books open, taking notes and highlighting key passages", "A2", "verbs", 208),
    ("teach", "öğretmek", "A teacher standing at a whiteboard pointing to a lesson while students watch attentively", "A2", "verbs", 209),
    ("listen", "dinlemek", "A person wearing headphones with eyes closed enjoying music or a podcast with full attention", "A2", "verbs", 210),
    ("speak", "konuşmak", "Two people facing each other in conversation, one gesturing with hands while the other listens", "A2", "verbs", 211),
    ("build", "inşa etmek", "Workers wearing hard hats on scaffolding constructing a building frame with beams and planks", "A2", "verbs", 212),
    ("clean", "temizlemek", "A person with rubber gloves scrubbing a surface with a brush and spray cleaner", "A2", "verbs", 213),
    ("fix", "tamir etmek", "A person using a wrench or screwdriver to repair a broken appliance on a worktable", "A2", "verbs", 214),
    ("choose", "seçmek", "A person standing in front of two different products in a store, comparing them carefully", "A2", "verbs", 215),
    ("find", "bulmak", "A person searching through a drawer and finally holding up the item they were looking for", "A2", "verbs", 216),
    ("forget", "unutmak", "A person leaving the house and stopping with a confused look, trying to remember something", "A2", "verbs", 217),
    ("remember", "hatırlamak", "A person touching their temple with a finger and smiling as a memory comes back to them", "A2", "verbs", 218),

    # ─── B1 – Nature & Environment ───
    ("desert", "çöl", "An endless expanse of golden sand dunes under a blazing sun with no water or shade in sight", "B1", "nature", 219),
    ("jungle", "orman/cangıl", "A dense tropical forest with enormous trees, tangled vines, and exotic colourful wildlife", "B1", "nature", 220),
    ("valley", "vadi", "A low-lying stretch of land between two mountain ranges with a river running through it", "B1", "nature", 221),
    ("waterfall", "şelale", "A cascading wall of water plunging from a great height into a misty pool below", "B1", "nature", 222),
    ("cliff", "uçurum", "A near-vertical rocky face dropping sharply from a high plateau to the sea or valley below", "B1", "nature", 223),
    ("volcano", "yanardağ", "A conical mountain with glowing orange lava and thick ash smoke erupting from its summit", "B1", "nature", 224),
    ("glacier", "buzul", "A massive slow-moving river of ancient blue-white ice carved between mountain peaks", "B1", "nature", 225),
    ("earthquake", "deprem", "Cracked pavement, collapsed walls and a city reduced to rubble after violent ground shaking", "B1", "nature", 226),
    ("hurricane", "kasırga", "A massive rotating storm system with spiralling clouds and destructive winds seen from satellite", "B1", "nature", 227),
    ("island", "ada", "A piece of land completely surrounded by the sea, often tropical with palm trees and turquoise water", "B1", "nature", 228),
    ("cave", "mağara", "A dark hollow chamber inside a rocky hillside with stalactites hanging from the ceiling", "B1", "nature", 229),
    ("swamp", "bataklık", "A waterlogged area of land covered in still dark water with moss, reeds and twisted trees", "B1", "nature", 230),

    # ─── B1 – Technology ───
    ("computer", "bilgisayar", "A glowing screen on a desk connected to a keyboard and mouse for processing information", "B1", "technology", 231),
    ("internet", "internet", "A web of glowing data lines connecting devices across a digital world map", "B1", "technology", 232),
    ("password", "şifre", "A login screen showing a series of dots hiding characters typed for account security", "B1", "technology", 233),
    ("battery", "pil/batarya", "A smartphone screen showing the low battery warning icon in red at the top corner", "B1", "technology", 234),
    ("keyboard", "klavye", "Rows of lettered keys on a rectangular input device used to type text on a computer", "B1", "technology", 235),
    ("speaker", "hoparlör", "A box-shaped audio device emitting sound waves with a visible mesh grille on the front", "B1", "technology", 236),
    ("headphones", "kulaklık", "A pair of cushioned audio devices worn over the ears connected by an arched band", "B1", "technology", 237),
    ("camera", "kamera/fotoğraf makinesi", "A device with a lens pointed at a subject to capture a photograph or record video", "B1", "technology", 238),
    ("satellite", "uydu", "A metallic object with large solar panel wings orbiting high above the curved surface of the Earth", "B1", "technology", 239),
    ("microphone", "mikrofon", "A cylindrical device on a stand held close to the mouth to capture and amplify a voice", "B1", "technology", 240),
    ("printer", "yazıcı", "An office machine feeding in blank paper and outputting a printed page with text and images", "B1", "technology", 241),
    ("charger", "şarj aleti", "A cable with a plug connected to a power outlet and a phone, replenishing the device's battery", "B1", "technology", 242),

    # ─── B1 – Business & Work ───
    ("meeting", "toplantı", "A group of colleagues sitting around an oval table with laptops and notepads in a conference room", "B1", "business", 243),
    ("contract", "sözleşme", "A multi-page legal document with signatures and official stamps at the bottom of the last page", "B1", "business", 244),
    ("salary", "maaş", "A bank statement showing a regular monthly payment credited to an employee's account", "B1", "business", 245),
    ("budget", "bütçe", "A spreadsheet with columns of income and expenses balanced against a total figure", "B1", "business", 246),
    ("manager", "yönetici", "A suited professional in a glass-walled office reviewing documents with a team member", "B1", "business", 247),
    ("employee", "çalışan", "An office worker at a desk with a computer, taking notes and answering a phone call", "B1", "business", 248),
    ("customer", "müşteri", "A person in a shop selecting items from a shelf and placing them in a shopping basket", "B1", "business", 249),
    ("profit", "kar", "An upward trending graph with the final bar much higher than the first, showing business growth", "B1", "business", 250),
    ("deadline", "son tarih", "A calendar with a date circled in red and a clock ticking down next to a stack of papers", "B1", "business", 251),
    ("invoice", "fatura", "A printed document listing goods or services provided with prices and a total amount due", "B1", "business", 252),
    ("colleague", "iş arkadaşı", "Two coworkers at adjacent desks collaborating on a shared document on their screens", "B1", "business", 253),

    # ─── B1 – Health ───
    ("medicine", "ilaç", "A row of orange prescription bottles with labels on a pharmacy shelf", "B1", "health", 254),
    ("vaccine", "aşı", "A doctor drawing liquid into a syringe next to a small glass vial labeled for immunisation", "B1", "health", 255),
    ("surgery", "ameliyat", "Surgeons in sterile gowns and masks bent over a patient under bright operating theatre lights", "B1", "health", 256),
    ("fever", "ateş", "A person lying in bed with a flushed face, a thermometer in their mouth and a cold cloth on their forehead", "B1", "health", 257),
    ("bandage", "bandaj", "A white gauze wrap wound firmly around an injured arm or leg to protect a wound", "B1", "health", 258),
    ("exercise", "egzersiz", "A person at a gym lifting weights or running on a treadmill in workout clothing", "B1", "health", 259),
    ("nutrition", "beslenme", "A colourful plate divided into portions of protein, vegetables, grains, and fruit", "B1", "health", 260),
    ("allergy", "alerji", "A person sneezing near flowers with watery eyes and a red irritated nose reaction", "B1", "health", 261),
    ("pharmacy", "eczane", "A brightly lit shop with organised shelves of medicines where a pharmacist helps a customer", "B1", "health", 262),
    ("dentist", "diş hekimi", "A person in a dental chair with a bright light overhead while a dentist examines their teeth", "B1", "health", 263),

    # ─── B1 – Education ───
    ("university", "üniversite", "A grand campus with stone buildings, archways, libraries and students walking between classes", "B1", "education", 264),
    ("degree", "derece/diploma", "A rolled parchment tied with a ribbon handed to a graduate in a black cap and gown", "B1", "education", 265),
    ("research", "araştırma", "A scientist in a lab coat surrounded by books and equipment collecting data on a clipboard", "B1", "education", 266),
    ("experiment", "deney", "Test tubes, Bunsen burners, and coloured liquids in a science laboratory", "B1", "education", 267),
    ("theory", "teori", "A physicist at a blackboard covered in complex equations and diagrams explaining a concept", "B1", "education", 268),
    ("evidence", "kanıt", "Photographs, documents, and fingerprint samples laid out on an examination table", "B1", "education", 269),
    ("argument", "argüman", "Two debaters at opposite podiums in a formal hall presenting opposing points of view", "B1", "education", 270),
    ("conclusion", "sonuç", "The final paragraph of a report circled, summarising all the key points discussed above", "B1", "education", 271),
    ("scholarship", "burs", "A student holding a letter of award for financial support to attend a prestigious university", "B1", "education", 272),
    ("assignment", "ödev/görev", "A student at a desk surrounded by textbooks working late under a lamp on a written task", "B1", "education", 273),

    # ─── B1 – Adjectives ───
    ("brilliant", "parlak/zeki", "A student smiling as they see a perfect score on their returned exam paper", "B1", "adjectives", 274),
    ("curious", "meraklı", "A child peering through a magnifying glass at a beetle on a leaf with intense interest", "B1", "adjectives", 275),
    ("generous", "cömert", "A person giving a large wrapped gift to someone else with a warm open smile", "B1", "adjectives", 276),
    ("patient", "sabırlı", "A person sitting calmly in a long queue, not fidgeting, reading a book peacefully", "B1", "adjectives", 277),
    ("flexible", "esnek", "A gymnast bending her body into an impressive arch, showing great physical agility", "B1", "adjectives", 278),
    ("ambitious", "hırslı", "A determined young professional climbing the rungs of a ladder with eyes fixed upward", "B1", "adjectives", 279),
    ("reliable", "güvenilir", "A person always arriving on time, meeting every commitment with consistency and dependability", "B1", "adjectives", 280),
    ("efficient", "verimli", "A worker completing tasks in record time with minimal wasted effort at a tidy desk", "B1", "adjectives", 281),
    ("creative", "yaratıcı", "An artist surrounded by colourful paints, sketches, and half-built sculptures in a messy studio", "B1", "adjectives", 282),
    ("peaceful", "huzurlu", "A person sitting by a still lake at dawn, everything quiet and perfectly serene", "B1", "adjectives", 283),

    # ─── B2 – Abstract & Society ───
    ("democracy", "demokrasi", "Citizens queuing outside a polling station to cast their vote in a free and fair election", "B2", "society", 284),
    ("justice", "adalet", "The scales of justice perfectly balanced with eyes blindfolded holding a sword and scales", "B2", "society", 285),
    ("freedom", "özgürlük", "An open birdcage door with a bird flying out into a bright open sky above the city", "B2", "society", 286),
    ("equality", "eşitlik", "Two people of different backgrounds standing side by side at the same level with equal signs", "B2", "society", 287),
    ("diversity", "çeşitlilik", "A circle of people of different ages, ethnicities and backgrounds holding hands together", "B2", "society", 288),
    ("poverty", "yoksulluk", "A contrast of a crumbling neighbourhood next to a gleaming modern skyline in the same city", "B2", "society", 289),
    ("corruption", "yolsuzluk", "A briefcase of cash being exchanged secretly under a table between two suited figures", "B2", "society", 290),
    ("revolution", "devrim", "Crowds gathering in a central plaza with banners raised demanding fundamental political change", "B2", "society", 291),
    ("propaganda", "propaganda", "Oversized posters with bold slogans covering a public building designed to influence opinion", "B2", "society", 292),
    ("prejudice", "önyargı", "A person turning away from someone different without giving them a chance to speak", "B2", "society", 293),

    # ─── B2 – Professional ───
    ("negotiate", "müzakere etmek", "Two business executives at a table exchanging documents and reaching out to shake hands", "B2", "professional", 294),
    ("implement", "uygulamak", "A project team executing steps from a detailed plan on a whiteboard with progress ticks", "B2", "professional", 295),
    ("evaluate", "değerlendirmek", "An assessor reviewing a completed project with a scoring rubric and marking criteria", "B2", "professional", 296),
    ("collaborate", "iş birliği yapmak", "Team members gathered around a table combining their individual contributions into one plan", "B2", "professional", 297),
    ("innovate", "yenilik yapmak", "An engineer sketching a groundbreaking prototype design on a whiteboard in a tech lab", "B2", "professional", 298),
    ("delegate", "devretmek", "A manager handing a folder of tasks to a team member, trusting them with responsibility", "B2", "professional", 299),
    ("strategy", "strateji", "Chess pieces arranged on a board representing the calculated long-term plan of a player", "B2", "professional", 300),
    ("portfolio", "portföy", "A designer presenting a bound collection of their best creative work at an interview", "B2", "professional", 301),
    ("milestone", "kilometre taşı", "A project timeline with a starred checkpoint marking a major achievement reached", "B2", "professional", 302),
    ("disruption", "aksaklık/bozucu değişim", "An established industry being upended by a newcomer with a completely different approach", "B2", "professional", 303),

    # ─── B2 – Environment ───
    ("ecosystem", "ekosistem", "A detailed diagram showing the complex web of connections between plants, animals and environment", "B2", "environment", 304),
    ("biodiversity", "biyoçeşitlilik", "A rainforest teeming with colourful birds, insects, mammals and exotic plant life", "B2", "environment", 305),
    ("sustainability", "sürdürülebilirlik", "Solar panels on rooftops, wind turbines and electric cars on a green energy-efficient city", "B2", "environment", 306),
    ("pollution", "kirlilik", "Grey smog hanging over a city skyline with factory chimneys belching black smoke", "B2", "environment", 307),
    ("recycling", "geri dönüşüm", "Colour-coded bins for glass, paper and plastic with sorted materials piled neatly beside them", "B2", "environment", 308),
    ("deforestation", "ormansızlaşma", "A forest half cleared with stumps and bare earth showing where dense trees once stood", "B2", "environment", 309),
    ("erosion", "erozyon", "Rainwater carving deep channels into exposed brown soil on a hillside losing its topsoil", "B2", "environment", 310),
    ("habitat", "yaşam alanı", "A natural environment perfectly suited to a species, like wetlands for wading birds", "B2", "environment", 311),
    ("emission", "emisyon", "A car exhaust releasing a cloud of carbon dioxide measured by a monitoring device", "B2", "environment", 312),
    ("conservation", "koruma/muhafaza", "A ranger monitoring endangered animals in a protected nature reserve with binoculars", "B2", "environment", 313),

    # ─── B2 – Advanced Adjectives ───
    ("sophisticated", "sofistike/karmaşık", "An elegantly designed interior with precise details showing refined taste and complexity", "B2", "adjectives", 314),
    ("controversial", "tartışmalı", "A town meeting erupting into heated debate with people on both sides raising their hands", "B2", "adjectives", 315),
    ("vulnerable", "savunmasız", "A small creature exposed in an open space with no shelter or protection nearby", "B2", "adjectives", 316),
    ("transparent", "şeffaf", "A glass-walled office where everything inside is fully visible to everyone passing outside", "B2", "adjectives", 317),
    ("inevitable", "kaçınılmaz", "A ticking clock next to an event that is clearly about to happen with no way to prevent it", "B2", "adjectives", 318),
    ("sustainable", "sürdürülebilir", "Energy sources and systems designed to last indefinitely without depleting natural resources", "B2", "adjectives", 319),
    ("overwhelming", "ezici/bunaltıcı", "A person buried under a towering pile of work files with a look of complete overload", "B2", "adjectives", 320),
    ("comprehensive", "kapsamlı", "A thick manual covering every single aspect of a topic from beginning to advanced level", "B2", "adjectives", 321),

    # ─── C1 – Advanced Academic ───
    ("ambiguous", "belirsiz/muğlak", "A sentence that could be understood in two completely different and contradictory ways", "C1", "academic", 322),
    ("empirical", "ampirik", "Scientists collecting data through direct observation and controlled experiments in the field", "C1", "academic", 323),
    ("hypothesis", "hipotez", "A researcher writing a testable prediction on a whiteboard before beginning an experiment", "C1", "academic", 324),
    ("methodology", "metodoloji", "A detailed research plan outlining the exact steps and tools to be used in a study", "C1", "academic", 325),
    ("phenomenon", "fenomen", "An extraordinary natural event that scientists observe, document and seek to explain", "C1", "academic", 326),
    ("paradigm", "paradigma", "An old world map beside a modern one showing how fundamentally the entire framework shifted", "C1", "academic", 327),
    ("inference", "çıkarım", "A detective examining clues and drawing a logical conclusion from indirect evidence", "C1", "academic", 328),
    ("correlation", "korelasyon", "A scatter plot showing two variables moving together in the same direction over time", "C1", "academic", 329),
    ("implication", "çıkarım/anlam", "A diagram showing how one event leads to a chain of indirect but significant consequences", "C1", "academic", 330),
    ("synthesis", "sentez", "A researcher combining findings from many separate sources into one unified framework", "C1", "academic", 331),

    # ─── C1 – Abstract Concepts ───
    ("autonomy", "özerklik", "A person confidently making their own independent decisions without needing others' approval", "C1", "abstract", 332),
    ("cognition", "biliş", "A diagram of the human brain with highlighted regions representing thought and memory processes", "C1", "abstract", 333),
    ("resilience", "dayanıklılık", "A bent but unbroken tree standing tall after a powerful storm has passed through", "C1", "abstract", 334),
    ("skepticism", "şüphecilik", "A person raising an eyebrow and questioning a claim before accepting any evidence at face value", "C1", "abstract", 335),
    ("integrity", "dürüstlük/bütünlük", "A person refusing a bribe and walking away from an envelope of money on a desk", "C1", "abstract", 336),
    ("rhetoric", "retorik", "A powerful orator at a podium using language and gesture to persuade a large audience", "C1", "abstract", 337),
    ("pragmatic", "pragmatik/pratik", "A problem-solver choosing the simplest workable solution rather than the most idealistic one", "C1", "abstract", 338),
    ("subjective", "öznel", "Two people looking at the same abstract painting and expressing completely different reactions", "C1", "abstract", 339),
    ("ideology", "ideoloji", "A political map with colour-coded regions each representing a different system of belief", "C1", "abstract", 340),
    ("perception", "algı", "An optical illusion that can be seen as either a young woman or an old one depending on viewpoint", "C1", "abstract", 341),

    # ─── C1 – Advanced Verbs ───
    ("scrutinize", "incelemek/denetlemek", "An auditor with a magnifying glass examining every line of a financial report on a desk", "C1", "verbs", 342),
    ("contemplate", "düşünmek/tefekkür etmek", "A philosopher sitting alone in a quiet room staring at the horizon in deep reflective thought", "C1", "verbs", 343),
    ("articulate", "açıkça ifade etmek", "A speaker carefully choosing precise words to explain a complex idea in perfectly clear terms", "C1", "verbs", 344),
    ("undermine", "zayıflatmak", "A structure with its foundations slowly being eroded causing the whole building to tilt dangerously", "C1", "verbs", 345),
    ("facilitate", "kolaylaştırmak", "A workshop leader helping two groups communicate better and find a shared working solution", "C1", "verbs", 346),
    ("acknowledge", "kabul etmek/tanımak", "A person nodding and accepting that the other person's point of view has real merit", "C1", "verbs", 347),
    ("distinguish", "ayırt etmek", "Two nearly identical objects side by side with an expert pointing to the subtle difference", "C1", "verbs", 348),
    ("anticipate", "öngörmek", "A chess player already looking several moves ahead, planning for every possible opponent response", "C1", "verbs", 349),
    ("jeopardize", "tehlikeye atmak", "A person making a reckless decision that puts a carefully built successful project at serious risk", "C1", "verbs", 350),
    ("reconcile", "uzlaştırmak/bağdaştırmak", "Two people who disagreed sitting back down together and finding common ground to move forward", "C1", "verbs", 351),

    # ─── C2 – Proficiency Level ───
    ("ubiquitous", "her yerde mevcut", "The same brand logo appearing simultaneously on phones, billboards, laptops, cups and clothing everywhere", "C2", "advanced", 352),
    ("ephemeral", "geçici/kısa ömürlü", "A soap bubble floating in the air for a brief moment before silently vanishing without a trace", "C2", "advanced", 353),
    ("serendipity", "şans eseri buluş", "A scientist accidentally spilling a chemical and discovering an entirely new compound by chance", "C2", "advanced", 354),
    ("juxtaposition", "yan yana koyma/karşıtlık", "A photograph showing a luxury penthouse directly above a cramped slum in the same city block", "C2", "advanced", 355),
    ("zeitgeist", "devrin ruhu", "A collage of news headlines, fashion trends and viral moments that define a particular decade", "C2", "advanced", 356),
    ("quintessential", "en tipik örnek", "An image so perfectly representing its category that it could serve as the textbook definition", "C2", "advanced", 357),
    ("melancholy", "melankolik hüzün", "A person sitting by a rain-streaked window watching leaves fall with a wistful faraway look", "C2", "advanced", 358),
    ("eloquent", "akıcı/güzel konuşan", "A speaker holding an audience completely spellbound with beautifully chosen and perfectly delivered words", "C2", "advanced", 359),
    ("ambivalence", "çelişkili duygular", "A person standing at a crossroads unable to move left or right, pulled equally by both options", "C2", "advanced", 360),
    ("idiosyncratic", "kendine özgü/alışılmadık", "An artist whose completely unique style is instantly recognisable and unlike anything else", "C2", "advanced", 361),
    ("vicarious", "dolaylı/başkasının yerine", "A person feeling the thrill of adventure purely through watching someone else's extreme sport footage", "C2", "advanced", 362),
    ("nuance", "nüans/ince fark", "A trained ear hearing the subtle tonal difference between two nearly identical musical notes", "C2", "advanced", 363),
    ("paradox", "paradoks", "A sign on a door saying 'This sentence is false' creating an endless loop of contradiction", "C2", "advanced", 364),
    ("pragmatism", "pragmatizm", "A builder choosing materials based purely on what works best rather than what looks impressive", "C2", "advanced", 365),
    ("contemplative", "düşünceli/tefekkürsel", "A monk sitting motionless in a stone garden at dawn in a state of deep inward meditation", "C2", "advanced", 366),

    # ─── Extra B1/B2 – Sports & Leisure ───
    ("tournament", "turnuva", "A bracket chart on a wall showing paired teams competing through rounds toward a final match", "B1", "sports", 367),
    ("championship", "şampiyonluk", "An athlete standing on a podium holding a gleaming trophy above their head in triumph", "B1", "sports", 368),
    ("referee", "hakem", "An official in a striped shirt blowing a whistle and showing a yellow card during a football match", "B1", "sports", 369),
    ("stadium", "stadyum", "A massive oval arena packed with thousands of cheering fans watching a sporting event", "B1", "sports", 370),
    ("marathon", "maraton", "Hundreds of runners in numbered bibs starting a 42-kilometre road race through a city", "B1", "sports", 371),
    ("medal", "madalya", "A round metal disc on a ribbon hung around an athlete's neck to recognise their achievement", "B1", "sports", 372),
    ("trophy", "kupa", "A tall silver or gold cup awarded to the winner of a competition displayed proudly on a shelf", "B1", "sports", 373),

    # ─── Extra A2/B1 – Art & Culture ───
    ("gallery", "galeri", "White walls displaying large framed artworks in a quiet modern museum with a polished floor", "A2", "culture", 374),
    ("sculpture", "heykel", "A three-dimensional carved stone or bronze figure displayed on a pedestal in a public square", "B1", "culture", 375),
    ("orchestra", "orkestra", "Dozens of musicians in formal attire playing different instruments together on a concert stage", "B1", "culture", 376),
    ("theatre", "tiyatro", "A velvet-curtained stage with actors performing under spotlights to a seated audience", "A2", "culture", 377),
    ("festival", "festival", "Colourful outdoor stages, crowds of people, food stalls and live music at a summer celebration", "A2", "culture", 378),
    ("tradition", "gelenek", "Families gathered in the same way they have for generations to celebrate a cultural custom", "B1", "culture", 379),
    ("heritage", "miras", "Ancient stone ruins preserved as a landmark connecting the present to thousands of years of history", "B1", "culture", 380),

    # ─── Extra A2 – Travel ───
    ("passport", "pasaport", "A small booklet with a photo and personal details shown at an international border crossing", "A2", "travel", 381),
    ("luggage", "bagaj", "A large suitcase on wheels with a handle, stacked at an airport check-in desk", "A2", "travel", 382),
    ("visa", "vize", "A stamped page in a passport granting official permission to enter a foreign country", "A2", "travel", 383),
    ("destination", "varış noktası", "A map with a pin placed on the final location at the end of a planned travel route", "A2", "travel", 384),
    ("souvenir", "hediyelik eşya", "A small decorative item bought in a tourist shop to remember a place visited abroad", "A2", "travel", 385),

    # ─── Extra B2 – Science & Medicine ───
    ("diagnosis", "teşhis", "A doctor reviewing test results and scan images to determine what illness a patient has", "B2", "health", 386),
    ("symptom", "belirti", "A patient describing a fever, cough and fatigue to a doctor who takes careful notes", "B2", "health", 387),
    ("pandemic", "pandemi", "A world map with red zones spreading across continents showing a global health crisis", "B2", "health", 388),
    ("chromosome", "kromozom", "A magnified image under a microscope showing paired DNA strands coiled into X-shaped structures", "B2", "science", 389),
    ("gravity", "yerçekimi", "An apple falling from a tree branch toward the ground illustrating the force pulling objects down", "B2", "science", 390),
    ("molecule", "molekül", "A 3D model of atoms bonded together forming the smallest unit of a chemical compound", "B2", "science", 391),
    ("atmosphere", "atmosfer", "Layers of blue gas surrounding the Earth seen from space protecting the planet from radiation", "B2", "science", 392),
    ("evolution", "evrim", "A sequence of figures from a simple four-legged creature progressively transforming into an upright human", "B2", "science", 393),

    # ─── Extra B1 – Finance ───
    ("loan", "kredi/borç", "A person signing paperwork at a bank desk to borrow a sum of money to be repaid with interest", "B1", "finance", 394),
    ("interest", "faiz/ilgi", "A percentage rate printed on a bank statement showing how much extra is owed on borrowed money", "B1", "finance", 395),
    ("investment", "yatırım", "A graph showing money placed into stocks or property growing in value over time", "B1", "finance", 396),
    ("savings", "tasarruf", "A piggy bank being filled coin by coin to build up a reserve of money for the future", "B1", "finance", 397),
    ("currency", "döviz/para birimi", "A collection of banknotes from different countries spread out on a table", "B1", "finance", 398),
    ("tax", "vergi", "A government form listing income and deductions used to calculate money owed to the state", "B1", "finance", 399),
    ("economy", "ekonomi", "A large circular diagram showing the flow of money between consumers, businesses and government", "B1", "finance", 400),

    # ─── Extra A1/A2 – Miscellaneous Common ───
    ("pencil", "kalem", "A wooden stick with a graphite core sharpened to a point used to draw or write on paper", "A1", "stationery", 401),
    ("paper", "kağıt", "A flat white sheet used for writing, drawing or printing, stacked neatly on a desk", "A1", "stationery", 402),
    ("phone", "telefon", "A rectangular touchscreen device held in the hand used to call, text and browse the internet", "A1", "technology", 403),
    ("television", "televizyon", "A flat screen on a wall displaying moving images and sound for home entertainment", "A1", "household", 404),
    ("music", "müzik", "Musical notes floating from a piano with vibrations in the air felt by a listening crowd", "A1", "culture", 405),
    ("photo", "fotoğraf", "A printed or digital image capturing a frozen moment in time from a camera", "A1", "culture", 406),
    ("letter", "mektup/harf", "A handwritten note on folded paper placed inside an envelope addressed and stamped for mailing", "A1", "communication", 407),
    ("map", "harita", "A flat representation of a geographic area with roads, rivers and landmarks drawn on it", "A1", "travel", 408),
    ("money", "para", "A collection of paper notes and metal coins of various denominations stacked on a surface", "A1", "finance", 409),
    ("ticket", "bilet", "A small printed card granting access to a concert, film, bus or sports event when shown at the entrance", "A1", "travel", 410),
]
