import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import coursesRouter from "./courses";
import modulesRouter from "./modules";
import lessonsRouter from "./lessons";
import liveClassesRouter from "./live-classes";
import quizzesRouter from "./quizzes";
import progressRouter from "./progress";
import certificatesRouter from "./certificates";
import messagesRouter from "./messages";
import leaderboardRouter from "./leaderboard";
import dashboardRouter from "./dashboard";
import corporateRouter from "./corporate";
import adminCompaniesRouter from "./admin-companies";
import adminGroupsRouter from "./admin-groups";
import adminSpeakingClubsRouter from "./admin-speaking-clubs";
import teacherRouter from "./teacher";
import quizImportRouter from "./quiz-import";
import studentRouter from "./student";
import forumRouter from "./forum";
import materialsRouter from "./materials";
import pronunciationRouter from "./pronunciation";
import writingRouter from "./writing";
import marketingRouter from "./marketing";
import activityRouter from "./activity";
import featureSettingsRouter from "./feature-settings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(corporateRouter);
router.use(adminCompaniesRouter);
router.use(adminGroupsRouter);
router.use(adminSpeakingClubsRouter);
router.use(teacherRouter);
router.use(quizImportRouter);
router.use(studentRouter);
router.use(forumRouter);
router.use(usersRouter);
router.use(coursesRouter);
router.use(modulesRouter);
router.use(lessonsRouter);
router.use(liveClassesRouter);
router.use(quizzesRouter);
router.use(progressRouter);
router.use(certificatesRouter);
router.use(messagesRouter);
router.use(leaderboardRouter);
router.use(dashboardRouter);
router.use(materialsRouter);
router.use(pronunciationRouter);
router.use(writingRouter);
router.use(marketingRouter);
router.use(activityRouter);
router.use(featureSettingsRouter);

export default router;
