// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-guide/BrandGuide.tsx": () => import("../components/mockups/brand-guide/BrandGuide.tsx"),
  "./components/mockups/sim-mode/SimMode.tsx": () => import("../components/mockups/sim-mode/SimMode.tsx")
};
