// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-guide/BrandGuide.tsx": () => import("../components/mockups/brand-guide/BrandGuide.tsx"),
  "./components/mockups/instagram-post/AiStudioPost.tsx": () => import("../components/mockups/instagram-post/AiStudioPost.tsx"),
  "./components/mockups/instagram-post/CoachPost.tsx": () => import("../components/mockups/instagram-post/CoachPost.tsx"),
  "./components/mockups/instagram-post/FoundersPost.tsx": () => import("../components/mockups/instagram-post/FoundersPost.tsx"),
  "./components/mockups/instagram-post/TeamPost.tsx": () => import("../components/mockups/instagram-post/TeamPost.tsx"),
  "./components/mockups/instagram-post/TrilogyPost.tsx": () => import("../components/mockups/instagram-post/TrilogyPost.tsx"),
  "./components/mockups/sim-mode/SimMode.tsx": () => import("../components/mockups/sim-mode/SimMode.tsx")
};
