export const VOCAB_WORDS = [
  { word: `cat`, turkish: `kedi`, imagePrompt: `A small furry animal with whiskers and a long tail, often curled up sleeping or chasing a ball of yarn`, level: `A1`, category: `animals` },
  { word: `dog`, turkish: `köpek`, imagePrompt: `A loyal four-legged animal with floppy ears and a wagging tail, running through a green park`, level: `A1`, category: `animals` },
  { word: `bird`, turkish: `kuş`, imagePrompt: `A feathered creature with wings perched on a branch, opening its beak to sing a melody`, level: `A1`, category: `animals` },
  { word: `fish`, turkish: `balık`, imagePrompt: `A shiny scaled creature swimming gracefully through clear blue water, blowing tiny bubbles`, level: `A1`, category: `animals` },
  { word: `horse`, turkish: `at`, imagePrompt: `A large powerful animal with a flowing mane galloping across an open meadow`, level: `A1`, category: `animals` },
  { word: `cow`, turkish: `inek`, imagePrompt: `A large black-and-white spotted animal standing in a green field, being milked by a farmer`, level: `A1`, category: `animals` },
  { word: `pig`, turkish: `domuz`, imagePrompt: `A plump pink animal with a curly tail rolling happily in a muddy puddle on a farm`, level: `A1`, category: `animals` },
  { word: `sheep`, turkish: `koyun`, imagePrompt: `A fluffy white woolly animal grazing peacefully on a hillside covered in green grass`, level: `A1`, category: `animals` },
  { word: `duck`, turkish: `ördek`, imagePrompt: `A plump bird with a flat orange beak waddling beside a pond and splashing in the water`, level: `A1`, category: `animals` },
  { word: `rabbit`, turkish: `tavşan`, imagePrompt: `A small fluffy creature with long ears and a cotton tail nibbling on a carrot`, level: `A1`, category: `animals` },
  { word: `bear`, turkish: `ayı`, imagePrompt: `A large furry animal with a round face and big paws walking through a dense forest`, level: `A1`, category: `animals` },
  { word: `lion`, turkish: `aslan`, imagePrompt: `A majestic big cat with a golden mane resting on a rock in the savanna`, level: `A1`, category: `animals` },
  { word: `tiger`, turkish: `kaplan`, imagePrompt: `A striped orange and black big cat crouching low in tall jungle grass`, level: `A1`, category: `animals` },
  { word: `elephant`, turkish: `fil`, imagePrompt: `An enormous grey animal with a long trunk, large ears and tusks walking slowly across the plains`, level: `A1`, category: `animals` },
  { word: `monkey`, turkish: `maymun`, imagePrompt: `A small agile animal with a long tail swinging from branch to branch high in a tropical tree`, level: `A1`, category: `animals` },
  { word: `snake`, turkish: `yılan`, imagePrompt: `A long slender reptile without legs gliding silently through dry leaves on the forest floor`, level: `A1`, category: `animals` },
  { word: `frog`, turkish: `kurbağa`, imagePrompt: `A small green amphibian with bulging eyes sitting on a lily pad and leaping into a pond`, level: `A1`, category: `animals` },
  { word: `butterfly`, turkish: `kelebek`, imagePrompt: `A delicate winged insect with colorful patterned wings resting on a bright flower`, level: `A1`, category: `animals` },
  { word: `ant`, turkish: `karınca`, imagePrompt: `A tiny six-legged insect marching in a long line across a picnic blanket carrying food`, level: `A1`, category: `animals` },
  { word: `bee`, turkish: `arı`, imagePrompt: `A yellow and black striped flying insect hovering over flowers collecting nectar`, level: `A1`, category: `animals` },
  { word: `red`, turkish: `kırmızı`, imagePrompt: `The bright fiery color of a ripe tomato, a fire truck, and a Valentine's heart`, level: `A1`, category: `colors` },
  { word: `blue`, turkish: `mavi`, imagePrompt: `The calming color of a clear sky on a sunny day and the deep ocean water`, level: `A1`, category: `colors` },
  { word: `green`, turkish: `yeşil`, imagePrompt: `The fresh vibrant color of new leaves, grass, and the forest in springtime`, level: `A1`, category: `colors` },
  { word: `yellow`, turkish: `sarı`, imagePrompt: `The cheerful bright color of sunflowers, ripe bananas, and the midday sun`, level: `A1`, category: `colors` },
  { word: `orange`, turkish: `turuncu`, imagePrompt: `The warm vivid color of autumn leaves, ripe citrus fruit, and a glowing sunset`, level: `A1`, category: `colors` },
  { word: `purple`, turkish: `mor`, imagePrompt: `The rich royal color of lavender flowers, grapes, and royal robes`, level: `A1`, category: `colors` },
  { word: `white`, turkish: `beyaz`, imagePrompt: `The pure clean color of fresh snow, a blank sheet of paper, and fluffy clouds`, level: `A1`, category: `colors` },
  { word: `black`, turkish: `siyah`, imagePrompt: `The deep dark color of the night sky, coal, and a sleek luxury car`, level: `A1`, category: `colors` },
  { word: `brown`, turkish: `kahverengi`, imagePrompt: `The earthy warm color of tree bark, freshly brewed coffee, and chocolate`, level: `A1`, category: `colors` },
  { word: `pink`, turkish: `pembe`, imagePrompt: `The soft delicate color of rose petals, cherry blossoms, and flamingo feathers`, level: `A1`, category: `colors` },
  { word: `mother`, turkish: `anne`, imagePrompt: `A caring woman hugging her child tightly with a warm loving smile in a cozy home`, level: `A1`, category: `family` },
  { word: `father`, turkish: `baba`, imagePrompt: `A man lifting his laughing child onto his shoulders in a sunny backyard`, level: `A1`, category: `family` },
  { word: `sister`, turkish: `kız kardeş`, imagePrompt: `Two girls sharing a book together, one older pointing at the pages to help the younger one read`, level: `A1`, category: `family` },
  { word: `brother`, turkish: `erkek kardeş`, imagePrompt: `Two boys playing catch in the garden, laughing and running around together`, level: `A1`, category: `family` },
  { word: `baby`, turkish: `bebek`, imagePrompt: `A tiny chubby infant wrapped in a soft blanket sleeping peacefully in a crib`, level: `A1`, category: `family` },
  { word: `grandmother`, turkish: `büyükanne`, imagePrompt: `An elderly woman with silver hair knitting in a rocking chair by a warm fireplace`, level: `A1`, category: `family` },
  { word: `grandfather`, turkish: `büyükbaba`, imagePrompt: `An old man with glasses sitting in a garden telling stories to grandchildren gathered around him`, level: `A1`, category: `family` },
  { word: `family`, turkish: `aile`, imagePrompt: `A group of parents and children sitting together at a dining table sharing a meal and laughing`, level: `A1`, category: `family` },
  { word: `head`, turkish: `baş`, imagePrompt: `The top round part of the body where the face, eyes, and brain are located`, level: `A1`, category: `body` },
  { word: `hand`, turkish: `el`, imagePrompt: `Five fingers attached to a palm, used for grasping, writing, and waving hello`, level: `A1`, category: `body` },
  { word: `foot`, turkish: `ayak`, imagePrompt: `The lower end of the leg with five toes used for standing, walking, and kicking a ball`, level: `A1`, category: `body` },
  { word: `eye`, turkish: `göz`, imagePrompt: `A round organ on the face used for seeing, framed by eyelashes and eyebrows`, level: `A1`, category: `body` },
  { word: `ear`, turkish: `kulak`, imagePrompt: `A curved organ on the side of the head used for hearing sounds and music`, level: `A1`, category: `body` },
  { word: `nose`, turkish: `burun`, imagePrompt: `The pointed organ in the center of the face used for breathing and smelling flowers`, level: `A1`, category: `body` },
  { word: `mouth`, turkish: `ağız`, imagePrompt: `The opening on the face with lips and teeth used for speaking, eating, and smiling`, level: `A1`, category: `body` },
  { word: `hair`, turkish: `saç`, imagePrompt: `The strands growing from the top of the head that can be cut, styled, and colored`, level: `A1`, category: `body` },
  { word: `arm`, turkish: `kol`, imagePrompt: `The long limb connecting the shoulder to the hand used for reaching and carrying`, level: `A1`, category: `body` },
  { word: `leg`, turkish: `bacak`, imagePrompt: `The long limb connecting the hip to the foot used for walking, running, and jumping`, level: `A1`, category: `body` },
  { word: `apple`, turkish: `elma`, imagePrompt: `A round smooth fruit that is red or green, sweet or tangy, often eaten as a healthy snack`, level: `A1`, category: `food` },
  { word: `bread`, turkish: `ekmek`, imagePrompt: `A baked food made from flour and yeast, golden-brown outside and soft inside, sliced for sandwiches`, level: `A1`, category: `food` },
  { word: `milk`, turkish: `süt`, imagePrompt: `A white creamy liquid from cows poured into a glass or used to make cheese and butter`, level: `A1`, category: `food` },
  { word: `water`, turkish: `su`, imagePrompt: `A clear colorless liquid essential for life, poured into a glass or flowing from a tap`, level: `A1`, category: `food` },
  { word: `egg`, turkish: `yumurta`, imagePrompt: `An oval shell containing a yolk and white, cracked into a pan and fried for breakfast`, level: `A1`, category: `food` },
  { word: `rice`, turkish: `pirinç`, imagePrompt: `Small white grains cooked in boiling water and served in a bowl as a staple meal`, level: `A1`, category: `food` },
  { word: `cake`, turkish: `kek`, imagePrompt: `A sweet baked dessert decorated with colorful frosting and candles for a birthday celebration`, level: `A1`, category: `food` },
  { word: `soup`, turkish: `çorba`, imagePrompt: `A hot liquid dish with vegetables and sometimes meat served in a bowl with a spoon`, level: `A1`, category: `food` },
  { word: `cheese`, turkish: `peynir`, imagePrompt: `A dairy product made from milk, yellow or white in color, sliced and placed on a cracker`, level: `A1`, category: `food` },
  { word: `coffee`, turkish: `kahve`, imagePrompt: `A dark aromatic hot drink made from ground roasted beans, poured steaming into a white cup`, level: `A1`, category: `food` },
  { word: `tea`, turkish: `çay`, imagePrompt: `A warm drink made by steeping dried leaves in hot water, served in a cup with a saucer`, level: `A1`, category: `food` },
  { word: `pizza`, turkish: `pizza`, imagePrompt: `A round flat bread topped with tomato sauce, melted cheese, and colorful toppings baked in an oven`, level: `A1`, category: `food` },
  { word: `shirt`, turkish: `gömlek`, imagePrompt: `A garment worn on the upper body with a collar, buttons down the front, and long or short sleeves`, level: `A1`, category: `clothing` },
  { word: `shoes`, turkish: `ayakkabı`, imagePrompt: `A pair of foot coverings with soles and laces placed neatly on the floor`, level: `A1`, category: `clothing` },
  { word: `hat`, turkish: `şapka`, imagePrompt: `A head covering with a brim that protects from sun or rain, placed on top of the head`, level: `A1`, category: `clothing` },
  { word: `dress`, turkish: `elbise`, imagePrompt: `A one-piece garment worn by women and girls that covers from shoulders to below the knees`, level: `A1`, category: `clothing` },
  { word: `coat`, turkish: `palto`, imagePrompt: `A long warm outer garment worn over other clothes in cold or rainy weather`, level: `A1`, category: `clothing` },
  { word: `bag`, turkish: `çanta`, imagePrompt: `A container with handles used for carrying belongings to school, work, or the market`, level: `A1`, category: `clothing` },
  { word: `glasses`, turkish: `gözlük`, imagePrompt: `A frame with two lenses worn on the face to help someone see more clearly`, level: `A1`, category: `clothing` },
  { word: `house`, turkish: `ev`, imagePrompt: `A building with walls, windows, a roof and a door where a family lives together`, level: `A1`, category: `house` },
  { word: `door`, turkish: `kapı`, imagePrompt: `A hinged panel in a wall that opens and closes to let people enter or leave a room`, level: `A1`, category: `house` },
  { word: `window`, turkish: `pencere`, imagePrompt: `A glass-covered opening in a wall letting light in and offering a view of the outside`, level: `A1`, category: `house` },
  { word: `table`, turkish: `masa`, imagePrompt: `A flat horizontal surface supported by four legs where people eat meals or work`, level: `A1`, category: `house` },
  { word: `chair`, turkish: `sandalye`, imagePrompt: `A seat with a back support and four legs where a person sits to eat, study or rest`, level: `A1`, category: `house` },
  { word: `bed`, turkish: `yatak`, imagePrompt: `A piece of furniture with a soft mattress and pillows where people sleep at night`, level: `A1`, category: `house` },
  { word: `kitchen`, turkish: `mutfak`, imagePrompt: `A room with a stove, oven, sink and refrigerator where meals are cooked and prepared`, level: `A1`, category: `house` },
  { word: `bathroom`, turkish: `banyo`, imagePrompt: `A room containing a bathtub or shower, sink and toilet used for personal hygiene`, level: `A1`, category: `house` },
  { word: `book`, turkish: `kitap`, imagePrompt: `Stacks of pages with text and pictures bound together with a cover, resting on a shelf`, level: `A1`, category: `house` },
  { word: `clock`, turkish: `saat`, imagePrompt: `A round device with two hands pointing to numbers displayed on a wall to show the time`, level: `A1`, category: `house` },
  { word: `sun`, turkish: `güneş`, imagePrompt: `A bright glowing sphere of light high in the blue sky warming the Earth on a clear day`, level: `A1`, category: `nature` },
  { word: `moon`, turkish: `ay`, imagePrompt: `A glowing silver circle visible in the dark night sky surrounded by stars`, level: `A1`, category: `nature` },
  { word: `star`, turkish: `yıldız`, imagePrompt: `A tiny bright light twinkling in the black night sky, part of a constellation pattern`, level: `A1`, category: `nature` },
  { word: `rain`, turkish: `yağmur`, imagePrompt: `Water droplets falling from grey clouds in the sky, making puddles on the pavement`, level: `A1`, category: `nature` },
  { word: `snow`, turkish: `kar`, imagePrompt: `White fluffy frozen water crystals falling from the sky and covering the ground in a white blanket`, level: `A1`, category: `nature` },
  { word: `flower`, turkish: `çiçek`, imagePrompt: `A colorful bloom with soft petals opening toward the sun, filling the air with sweet fragrance`, level: `A1`, category: `nature` },
  { word: `tree`, turkish: `ağaç`, imagePrompt: `A tall plant with a thick trunk, spreading branches, and green leaves reaching toward the sky`, level: `A1`, category: `nature` },
  { word: `grass`, turkish: `çimen`, imagePrompt: `Short green blades of plant covering the ground in a park where children play and picnic`, level: `A1`, category: `nature` },
  { word: `mountain`, turkish: `dağ`, imagePrompt: `A massive rocky peak rising high into the clouds with snow capping its summit`, level: `A1`, category: `nature` },
  { word: `sea`, turkish: `deniz`, imagePrompt: `A vast expanse of deep blue saltwater stretching to the horizon with waves crashing on the shore`, level: `A1`, category: `nature` },
  { word: `river`, turkish: `nehir`, imagePrompt: `A long flowing body of fresh water winding through valleys and forests toward the ocean`, level: `A1`, category: `nature` },
  { word: `sky`, turkish: `gökyüzü`, imagePrompt: `The vast blue canopy above the Earth with white clouds drifting and birds soaring`, level: `A1`, category: `nature` },
  { word: `car`, turkish: `araba`, imagePrompt: `A four-wheeled vehicle with an engine used to drive people from place to place on roads`, level: `A1`, category: `transport` },
  { word: `bus`, turkish: `otobüs`, imagePrompt: `A large vehicle with rows of seats carrying many passengers along a fixed route through the city`, level: `A1`, category: `transport` },
  { word: `train`, turkish: `tren`, imagePrompt: `A long vehicle with multiple carriages running on metal rails through cities and countryside`, level: `A1`, category: `transport` },
  { word: `boat`, turkish: `tekne`, imagePrompt: `A small water vessel with a hull floating on a river or lake, moved by oars or a motor`, level: `A1`, category: `transport` },
  { word: `plane`, turkish: `uçak`, imagePrompt: `A large winged aircraft that carries passengers through the sky between distant cities`, level: `A1`, category: `transport` },
  { word: `bike`, turkish: `bisiklet`, imagePrompt: `A two-wheeled vehicle with pedals and handlebars that a person rides by pedaling`, level: `A1`, category: `transport` },
  { word: `run`, turkish: `koşmak`, imagePrompt: `A person moving quickly on their feet with both legs lifting off the ground alternately`, level: `A1`, category: `verbs` },
  { word: `jump`, turkish: `atlamak`, imagePrompt: `A person bending their knees and springing up into the air off the ground`, level: `A1`, category: `verbs` },
  { word: `swim`, turkish: `yüzmek`, imagePrompt: `A person moving through water by moving their arms and kicking their legs`, level: `A1`, category: `verbs` },
  { word: `eat`, turkish: `yemek`, imagePrompt: `A person sitting at a table bringing food to their mouth with a fork and chewing`, level: `A1`, category: `verbs` },
  { word: `drink`, turkish: `içmek`, imagePrompt: `A person raising a glass to their lips and swallowing a liquid`, level: `A1`, category: `verbs` },
  { word: `sleep`, turkish: `uyumak`, imagePrompt: `A person lying in bed with closed eyes, a pillow under their head, in a quiet dark room`, level: `A1`, category: `verbs` },
  { word: `walk`, turkish: `yürümek`, imagePrompt: `A person moving forward on two feet at a steady pace along a sidewalk`, level: `A1`, category: `verbs` },
  { word: `read`, turkish: `okumak`, imagePrompt: `A person sitting in a chair holding an open book and looking carefully at the words on the page`, level: `A1`, category: `verbs` },
  { word: `write`, turkish: `yazmak`, imagePrompt: `A hand holding a pen and moving it across a sheet of paper making letters and words`, level: `A1`, category: `verbs` },
  { word: `play`, turkish: `oynamak`, imagePrompt: `Children laughing and running around on a colorful playground with swings and slides`, level: `A1`, category: `verbs` },
  { word: `dance`, turkish: `dans etmek`, imagePrompt: `A person moving their body rhythmically to music with arms extended and feet moving`, level: `A1`, category: `verbs` },
  { word: `sing`, turkish: `şarkı söylemek`, imagePrompt: `A person standing at a microphone with mouth open and eyes closed, performing a song`, level: `A1`, category: `verbs` },
  { word: `cook`, turkish: `pişirmek`, imagePrompt: `A person in an apron standing at a stove stirring a pot with steam rising from it`, level: `A1`, category: `verbs` },
  { word: `open`, turkish: `açmak`, imagePrompt: `Two hands gripping the handle of a closed door and pulling it wide open`, level: `A1`, category: `verbs` },
  { word: `close`, turkish: `kapatmak`, imagePrompt: `A hand reaching out and pushing a door shut until it clicks into the frame`, level: `A1`, category: `verbs` },
  { word: `big`, turkish: `büyük`, imagePrompt: `An enormous elephant standing next to a tiny mouse to show the difference in size`, level: `A1`, category: `adjectives` },
  { word: `small`, turkish: `küçük`, imagePrompt: `A tiny kitten fitting inside a teacup to show how little it is`, level: `A1`, category: `adjectives` },
  { word: `tall`, turkish: `uzun boylu`, imagePrompt: `A basketball player stretching to reach a very high shelf that shorter people cannot reach`, level: `A1`, category: `adjectives` },
  { word: `short`, turkish: `kısa boylu`, imagePrompt: `A child standing on tiptoes next to a very tall adult trying to reach the same height`, level: `A1`, category: `adjectives` },
  { word: `hot`, turkish: `sıcak`, imagePrompt: `Steam rising from a bowl of soup placed on a table showing the heat inside`, level: `A1`, category: `adjectives` },
  { word: `cold`, turkish: `soğuk`, imagePrompt: `A glass of water with ice cubes and frost forming on the outside surface`, level: `A1`, category: `adjectives` },
  { word: `fast`, turkish: `hızlı`, imagePrompt: `A racing car with motion blur zooming along a track at incredible speed`, level: `A1`, category: `adjectives` },
  { word: `slow`, turkish: `yavaş`, imagePrompt: `A tortoise taking careful deliberate steps along a path, moving unhurriedly`, level: `A1`, category: `adjectives` },
  { word: `happy`, turkish: `mutlu`, imagePrompt: `A person with a wide smile, bright eyes, and arms raised in a joyful expression`, level: `A1`, category: `adjectives` },
  { word: `sad`, turkish: `üzgün`, imagePrompt: `A person sitting alone with drooping shoulders, looking down with a sorrowful expression`, level: `A1`, category: `adjectives` },
  { word: `new`, turkish: `yeni`, imagePrompt: `A shiny unopened product still in its original packaging with a price tag attached`, level: `A1`, category: `adjectives` },
  { word: `old`, turkish: `eski`, imagePrompt: `A worn-out leather shoe with cracked soles and faded color showing years of use`, level: `A1`, category: `adjectives` },
  { word: `beautiful`, turkish: `güzel`, imagePrompt: `A stunning sunset with pink and orange colors reflecting on a calm lake surface`, level: `A1`, category: `adjectives` },
  { word: `clean`, turkish: `temiz`, imagePrompt: `A sparkling white plate just washed and dripping with water on a dish rack`, level: `A1`, category: `adjectives` },
  { word: `dirty`, turkish: `kirli`, imagePrompt: `Muddy boots with caked soil and stains left at the entrance of a clean house`, level: `A1`, category: `adjectives` },
  { word: `morning`, turkish: `sabah`, imagePrompt: `Golden sunlight streaming through curtains, a coffee mug steaming, a new day beginning`, level: `A1`, category: `time` },
  { word: `night`, turkish: `gece`, imagePrompt: `A dark sky filled with stars and a glowing moon above a quiet sleeping city`, level: `A1`, category: `time` },
  { word: `today`, turkish: `bugün`, imagePrompt: `A calendar page circled in red with the current date highlighted`, level: `A1`, category: `time` },
  { word: `week`, turkish: `hafta`, imagePrompt: `A calendar showing seven days from Monday to Sunday with each day labeled`, level: `A1`, category: `time` },
  { word: `year`, turkish: `yıl`, imagePrompt: `A page from a calendar showing all twelve months of the year arranged in a grid`, level: `A1`, category: `time` },
  { word: `wolf`, turkish: `kurt`, imagePrompt: `A grey furry wild animal with yellow eyes howling at the moon in a snowy forest`, level: `A2`, category: `animals` },
  { word: `fox`, turkish: `tilki`, imagePrompt: `A clever-looking red and white animal with a bushy tail sneaking through autumn leaves`, level: `A2`, category: `animals` },
  { word: `deer`, turkish: `geyik`, imagePrompt: `A graceful animal with spotted coat and branching antlers stepping quietly through the forest`, level: `A2`, category: `animals` },
  { word: `owl`, turkish: `baykuş`, imagePrompt: `A round-faced nocturnal bird with large yellow eyes perched silently on a branch at night`, level: `A2`, category: `animals` },
  { word: `parrot`, turkish: `papağan`, imagePrompt: `A brightly colored tropical bird with a curved beak sitting on a wooden perch and mimicking words`, level: `A2`, category: `animals` },
  { word: `crocodile`, turkish: `timsah`, imagePrompt: `A large reptile with a long jaw full of sharp teeth lying very still at the edge of a river`, level: `A2`, category: `animals` },
  { word: `penguin`, turkish: `penguen`, imagePrompt: `A black and white flightless bird waddling on ice in a frozen Antarctic landscape`, level: `A2`, category: `animals` },
  { word: `whale`, turkish: `balina`, imagePrompt: `The largest creature on Earth breaching from the ocean and splashing back down into the waves`, level: `A2`, category: `animals` },
  { word: `shark`, turkish: `köpekbalığı`, imagePrompt: `A powerful grey fish with a tall dorsal fin cutting through the ocean surface`, level: `A2`, category: `animals` },
  { word: `dolphin`, turkish: `yunus`, imagePrompt: `A sleek intelligent marine mammal leaping gracefully above the ocean waves`, level: `A2`, category: `animals` },
  { word: `eagle`, turkish: `kartal`, imagePrompt: `A large bird of prey with a hooked beak and powerful wings soaring high above a canyon`, level: `A2`, category: `animals` },
  { word: `camel`, turkish: `deve`, imagePrompt: `A large desert animal with a hump on its back walking slowly across golden sand dunes`, level: `A2`, category: `animals` },
  { word: `giraffe`, turkish: `zürafa`, imagePrompt: `The world's tallest animal with a long spotted neck stretching up to eat leaves from a treetop`, level: `A2`, category: `animals` },
  { word: `banana`, turkish: `muz`, imagePrompt: `A curved yellow fruit with a soft creamy interior, peeled and eaten as a sweet snack`, level: `A2`, category: `food` },
  { word: `strawberry`, turkish: `çilek`, imagePrompt: `A small red heart-shaped fruit with tiny seeds on its surface dipped in cream or chocolate`, level: `A2`, category: `food` },
  { word: `chocolate`, turkish: `çikolata`, imagePrompt: `A rich dark sweet treat made from cocoa, wrapped in foil and broken into squares`, level: `A2`, category: `food` },
  { word: `hamburger`, turkish: `hamburger`, imagePrompt: `A round beef patty with lettuce, tomato and cheese between two sesame seed buns`, level: `A2`, category: `food` },
  { word: `sandwich`, turkish: `sandviç`, imagePrompt: `Two slices of bread with various fillings like cheese, ham and vegetables pressed together`, level: `A2`, category: `food` },
  { word: `grape`, turkish: `üzüm`, imagePrompt: `Small round fruits growing in clusters on a vine, green or purple, sweet and juicy`, level: `A2`, category: `food` },
  { word: `watermelon`, turkish: `karpuz`, imagePrompt: `A large round green fruit with bright red juicy flesh filled with black seeds, eaten in slices`, level: `A2`, category: `food` },
  { word: `lemon`, turkish: `limon`, imagePrompt: `A bright yellow oval citrus fruit with very sour juice used to flavor food and drinks`, level: `A2`, category: `food` },
  { word: `potato`, turkish: `patates`, imagePrompt: `A starchy underground vegetable with brown skin, peeled and boiled, mashed or fried`, level: `A2`, category: `food` },
  { word: `tomato`, turkish: `domates`, imagePrompt: `A plump round red fruit used as a vegetable in salads and sauces, sliced on a cutting board`, level: `A2`, category: `food` },
  { word: `pasta`, turkish: `makarna`, imagePrompt: `Long thin noodles boiled in water and served with tomato sauce and cheese on a plate`, level: `A2`, category: `food` },
  { word: `salad`, turkish: `salata`, imagePrompt: `A bowl of mixed green leaves, tomatoes, cucumbers and other fresh vegetables tossed together`, level: `A2`, category: `food` },
  { word: `garlic`, turkish: `sarımsak`, imagePrompt: `A pungent white bulb divided into cloves used to add strong flavor to cooked dishes`, level: `A2`, category: `food` },
  { word: `onion`, turkish: `soğan`, imagePrompt: `A round layered vegetable with a papery skin that releases a sharp smell when peeled and cut`, level: `A2`, category: `food` },
  { word: `honey`, turkish: `bal`, imagePrompt: `A thick golden liquid made by bees from flower nectar, drizzled from a jar onto toast`, level: `A2`, category: `food` },
  { word: `butter`, turkish: `tereyağı`, imagePrompt: `A pale yellow creamy solid made from churned cream, spread onto warm bread with a knife`, level: `A2`, category: `food` },
  { word: `yogurt`, turkish: `yoğurt`, imagePrompt: `A thick white creamy dairy product made by fermenting milk, served in a bowl with fresh fruit`, level: `A2`, category: `food` },
  { word: `school`, turkish: `okul`, imagePrompt: `A large building with many classrooms where children sit at desks and learn from teachers`, level: `A2`, category: `places` },
  { word: `hospital`, turkish: `hastane`, imagePrompt: `A large medical building with doctors and nurses caring for patients in white rooms`, level: `A2`, category: `places` },
  { word: `library`, turkish: `kütüphane`, imagePrompt: `A quiet building lined with tall shelves of books where people sit and read in silence`, level: `A2`, category: `places` },
  { word: `market`, turkish: `pazar`, imagePrompt: `An outdoor area with colourful stalls selling fresh vegetables, fruit and local products`, level: `A2`, category: `places` },
  { word: `restaurant`, turkish: `restoran`, imagePrompt: `A place with tables set with napkins and cutlery where people order and eat prepared meals`, level: `A2`, category: `places` },
  { word: `hotel`, turkish: `otel`, imagePrompt: `A building with many numbered rooms where travellers stay overnight in comfortable beds`, level: `A2`, category: `places` },
  { word: `park`, turkish: `park`, imagePrompt: `An open green space with benches, trees and pathways where people walk and children play`, level: `A2`, category: `places` },
  { word: `beach`, turkish: `plaj`, imagePrompt: `A sandy shoreline beside the sea with waves rolling in and people sunbathing under umbrellas`, level: `A2`, category: `places` },
  { word: `airport`, turkish: `havalimanı`, imagePrompt: `A large terminal building with departure boards where planes take off and land on long runways`, level: `A2`, category: `places` },
  { word: `museum`, turkish: `müze`, imagePrompt: `A building with large halls displaying ancient artefacts and paintings behind glass cases`, level: `A2`, category: `places` },
  { word: `supermarket`, turkish: `süpermarket`, imagePrompt: `A large store with aisles of shelves stacked with packaged food and household goods`, level: `A2`, category: `places` },
  { word: `pharmacy`, turkish: `eczane`, imagePrompt: `A shop with shelves of medicines and vitamins where a pharmacist fills prescriptions`, level: `A2`, category: `places` },
  { word: `sunny`, turkish: `güneşli`, imagePrompt: `A bright blue sky without a single cloud with golden sunlight warming the landscape below`, level: `A2`, category: `weather` },
  { word: `rainy`, turkish: `yağmurlu`, imagePrompt: `Dark grey clouds releasing a steady downpour of rain onto wet streets and umbrellas`, level: `A2`, category: `weather` },
  { word: `cloudy`, turkish: `bulutlu`, imagePrompt: `A white and grey overcast sky with thick clouds blocking the sun on a mild day`, level: `A2`, category: `weather` },
  { word: `windy`, turkish: `rüzgarlı`, imagePrompt: `Tree branches bending dramatically, leaves swirling through the air, hair blowing sideways`, level: `A2`, category: `weather` },
  { word: `foggy`, turkish: `sisli`, imagePrompt: `A landscape where buildings and trees fade into a thick white mist reducing visibility`, level: `A2`, category: `weather` },
  { word: `stormy`, turkish: `fırtınalı`, imagePrompt: `Dark towering clouds with lightning bolts striking and heavy rain lashing a seascape`, level: `A2`, category: `weather` },
  { word: `freezing`, turkish: `dondurucu`, imagePrompt: `A thermometer showing well below zero with icicles hanging from rooftops and frozen ponds`, level: `A2`, category: `weather` },
  { word: `warm`, turkish: `ilık`, imagePrompt: `People relaxing outside in light clothing enjoying comfortable mild sunshine in a garden`, level: `A2`, category: `weather` },
  { word: `humid`, turkish: `nemli`, imagePrompt: `A tropical landscape with heat shimmer rising from the ground and people sweating in sticky air`, level: `A2`, category: `weather` },
  { word: `angry`, turkish: `kızgın`, imagePrompt: `A person with a furrowed brow, reddened face and clenched fists in a heated argument`, level: `A2`, category: `emotions` },
  { word: `excited`, turkish: `heyecanlı`, imagePrompt: `A person jumping up and down with wide eyes and arms raised in thrilled anticipation`, level: `A2`, category: `emotions` },
  { word: `surprised`, turkish: `şaşırmış`, imagePrompt: `A person with mouth wide open, eyebrows raised high, and eyes wide at an unexpected moment`, level: `A2`, category: `emotions` },
  { word: `bored`, turkish: `sıkılmış`, imagePrompt: `A person slumped in a chair, staring blankly at the ceiling with a heavy sigh`, level: `A2`, category: `emotions` },
  { word: `tired`, turkish: `yorgun`, imagePrompt: `A person with drooping eyelids, slumped posture, yawning widely after a long day of work`, level: `A2`, category: `emotions` },
  { word: `afraid`, turkish: `korkmuş`, imagePrompt: `A person with wide frightened eyes hiding behind a door in a dark hallway`, level: `A2`, category: `emotions` },
  { word: `proud`, turkish: `gururlu`, imagePrompt: `A person standing upright with a big smile holding a trophy or medal, chest puffed out`, level: `A2`, category: `emotions` },
  { word: `lonely`, turkish: `yalnız`, imagePrompt: `A single person sitting on a park bench far from others, watching people pass by`, level: `A2`, category: `emotions` },
  { word: `worried`, turkish: `endişeli`, imagePrompt: `A person biting their nails and pacing back and forth looking at their phone anxiously`, level: `A2`, category: `emotions` },
  { word: `calm`, turkish: `sakin`, imagePrompt: `A person sitting cross-legged in a peaceful garden with eyes closed, breathing slowly`, level: `A2`, category: `emotions` },
  { word: `cup`, turkish: `kupa/fincan`, imagePrompt: `A ceramic container with a handle filled with hot tea or coffee resting on a saucer`, level: `A2`, category: `household` },
  { word: `plate`, turkish: `tabak`, imagePrompt: `A round flat white dish holding a meal at a dining table set with cutlery`, level: `A2`, category: `household` },
  { word: `knife`, turkish: `bıçak`, imagePrompt: `A metal utensil with a sharp blade used for cutting food on a chopping board`, level: `A2`, category: `household` },
  { word: `spoon`, turkish: `kaşık`, imagePrompt: `A small oval bowl on a handle used for stirring soup and scooping soft foods`, level: `A2`, category: `household` },
  { word: `lamp`, turkish: `lamba`, imagePrompt: `A light fixture on a bedside table casting a warm yellow glow in a dim room`, level: `A2`, category: `household` },
  { word: `mirror`, turkish: `ayna`, imagePrompt: `A glass surface that reflects a clear image of the person standing in front of it`, level: `A2`, category: `household` },
  { word: `sofa`, turkish: `kanepe`, imagePrompt: `A large padded seat with armrests and a back where several people sit comfortably together`, level: `A2`, category: `household` },
  { word: `carpet`, turkish: `halı`, imagePrompt: `A soft patterned fabric covering a floor in a living room, warm underfoot`, level: `A2`, category: `household` },
  { word: `key`, turkish: `anahtar`, imagePrompt: `A small metal object with ridges that fits into a lock to open a door`, level: `A2`, category: `household` },
  { word: `towel`, turkish: `havlu`, imagePrompt: `A thick absorbent piece of cloth used to dry the body after bathing, hanging on a rack`, level: `A2`, category: `household` },
  { word: `pillow`, turkish: `yastık`, imagePrompt: `A soft rectangular cushion stuffed with filling placed under the head on a bed for sleep`, level: `A2`, category: `household` },
  { word: `umbrella`, turkish: `şemsiye`, imagePrompt: `A portable canopy on a metal frame opened above a person's head to protect from rain`, level: `A2`, category: `household` },
  { word: `buy`, turkish: `satın almak`, imagePrompt: `A person at a shop counter handing over money to a cashier in exchange for a product`, level: `A2`, category: `verbs` },
  { word: `sell`, turkish: `satmak`, imagePrompt: `A market vendor handing over a bag of goods to a customer who pays at a stall`, level: `A2`, category: `verbs` },
  { word: `travel`, turkish: `seyahat etmek`, imagePrompt: `A person with a suitcase at an airport looking up at a departures board with excitement`, level: `A2`, category: `verbs` },
  { word: `learn`, turkish: `öğrenmek`, imagePrompt: `A student sitting at a desk with books open, taking notes and highlighting key passages`, level: `A2`, category: `verbs` },
  { word: `teach`, turkish: `öğretmek`, imagePrompt: `A teacher standing at a whiteboard pointing to a lesson while students watch attentively`, level: `A2`, category: `verbs` },
  { word: `listen`, turkish: `dinlemek`, imagePrompt: `A person wearing headphones with eyes closed enjoying music or a podcast with full attention`, level: `A2`, category: `verbs` },
  { word: `speak`, turkish: `konuşmak`, imagePrompt: `Two people facing each other in conversation, one gesturing with hands while the other listens`, level: `A2`, category: `verbs` },
  { word: `build`, turkish: `inşa etmek`, imagePrompt: `Workers wearing hard hats on scaffolding constructing a building frame with beams and planks`, level: `A2`, category: `verbs` },
  { word: `fix`, turkish: `tamir etmek`, imagePrompt: `A person using a wrench or screwdriver to repair a broken appliance on a worktable`, level: `A2`, category: `verbs` },
  { word: `choose`, turkish: `seçmek`, imagePrompt: `A person standing in front of two different products in a store, comparing them carefully`, level: `A2`, category: `verbs` },
  { word: `find`, turkish: `bulmak`, imagePrompt: `A person searching through a drawer and finally holding up the item they were looking for`, level: `A2`, category: `verbs` },
  { word: `forget`, turkish: `unutmak`, imagePrompt: `A person leaving the house and stopping with a confused look, trying to remember something`, level: `A2`, category: `verbs` },
  { word: `remember`, turkish: `hatırlamak`, imagePrompt: `A person touching their temple with a finger and smiling as a memory comes back to them`, level: `A2`, category: `verbs` },
  { word: `desert`, turkish: `çöl`, imagePrompt: `An endless expanse of golden sand dunes under a blazing sun with no water or shade in sight`, level: `B1`, category: `nature` },
  { word: `jungle`, turkish: `orman/cangıl`, imagePrompt: `A dense tropical forest with enormous trees, tangled vines, and exotic colourful wildlife`, level: `B1`, category: `nature` },
  { word: `valley`, turkish: `vadi`, imagePrompt: `A low-lying stretch of land between two mountain ranges with a river running through it`, level: `B1`, category: `nature` },
  { word: `waterfall`, turkish: `şelale`, imagePrompt: `A cascading wall of water plunging from a great height into a misty pool below`, level: `B1`, category: `nature` },
  { word: `cliff`, turkish: `uçurum`, imagePrompt: `A near-vertical rocky face dropping sharply from a high plateau to the sea or valley below`, level: `B1`, category: `nature` },
  { word: `volcano`, turkish: `yanardağ`, imagePrompt: `A conical mountain with glowing orange lava and thick ash smoke erupting from its summit`, level: `B1`, category: `nature` },
  { word: `glacier`, turkish: `buzul`, imagePrompt: `A massive slow-moving river of ancient blue-white ice carved between mountain peaks`, level: `B1`, category: `nature` },
  { word: `earthquake`, turkish: `deprem`, imagePrompt: `Cracked pavement, collapsed walls and a city reduced to rubble after violent ground shaking`, level: `B1`, category: `nature` },
  { word: `hurricane`, turkish: `kasırga`, imagePrompt: `A massive rotating storm system with spiralling clouds and destructive winds seen from satellite`, level: `B1`, category: `nature` },
  { word: `island`, turkish: `ada`, imagePrompt: `A piece of land completely surrounded by the sea, often tropical with palm trees and turquoise water`, level: `B1`, category: `nature` },
  { word: `cave`, turkish: `mağara`, imagePrompt: `A dark hollow chamber inside a rocky hillside with stalactites hanging from the ceiling`, level: `B1`, category: `nature` },
  { word: `swamp`, turkish: `bataklık`, imagePrompt: `A waterlogged area of land covered in still dark water with moss, reeds and twisted trees`, level: `B1`, category: `nature` },
  { word: `computer`, turkish: `bilgisayar`, imagePrompt: `A glowing screen on a desk connected to a keyboard and mouse for processing information`, level: `B1`, category: `technology` },
  { word: `internet`, turkish: `internet`, imagePrompt: `A web of glowing data lines connecting devices across a digital world map`, level: `B1`, category: `technology` },
  { word: `password`, turkish: `şifre`, imagePrompt: `A login screen showing a series of dots hiding characters typed for account security`, level: `B1`, category: `technology` },
  { word: `battery`, turkish: `pil/batarya`, imagePrompt: `A smartphone screen showing the low battery warning icon in red at the top corner`, level: `B1`, category: `technology` },
  { word: `keyboard`, turkish: `klavye`, imagePrompt: `Rows of lettered keys on a rectangular input device used to type text on a computer`, level: `B1`, category: `technology` },
  { word: `speaker`, turkish: `hoparlör`, imagePrompt: `A box-shaped audio device emitting sound waves with a visible mesh grille on the front`, level: `B1`, category: `technology` },
  { word: `headphones`, turkish: `kulaklık`, imagePrompt: `A pair of cushioned audio devices worn over the ears connected by an arched band`, level: `B1`, category: `technology` },
  { word: `camera`, turkish: `kamera/fotoğraf makinesi`, imagePrompt: `A device with a lens pointed at a subject to capture a photograph or record video`, level: `B1`, category: `technology` },
  { word: `satellite`, turkish: `uydu`, imagePrompt: `A metallic object with large solar panel wings orbiting high above the curved surface of the Earth`, level: `B1`, category: `technology` },
  { word: `microphone`, turkish: `mikrofon`, imagePrompt: `A cylindrical device on a stand held close to the mouth to capture and amplify a voice`, level: `B1`, category: `technology` },
  { word: `printer`, turkish: `yazıcı`, imagePrompt: `An office machine feeding in blank paper and outputting a printed page with text and images`, level: `B1`, category: `technology` },
  { word: `charger`, turkish: `şarj aleti`, imagePrompt: `A cable with a plug connected to a power outlet and a phone, replenishing the device's battery`, level: `B1`, category: `technology` },
  { word: `meeting`, turkish: `toplantı`, imagePrompt: `A group of colleagues sitting around an oval table with laptops and notepads in a conference room`, level: `B1`, category: `business` },
  { word: `contract`, turkish: `sözleşme`, imagePrompt: `A multi-page legal document with signatures and official stamps at the bottom of the last page`, level: `B1`, category: `business` },
  { word: `salary`, turkish: `maaş`, imagePrompt: `A bank statement showing a regular monthly payment credited to an employee's account`, level: `B1`, category: `business` },
  { word: `budget`, turkish: `bütçe`, imagePrompt: `A spreadsheet with columns of income and expenses balanced against a total figure`, level: `B1`, category: `business` },
  { word: `manager`, turkish: `yönetici`, imagePrompt: `A suited professional in a glass-walled office reviewing documents with a team member`, level: `B1`, category: `business` },
  { word: `employee`, turkish: `çalışan`, imagePrompt: `An office worker at a desk with a computer, taking notes and answering a phone call`, level: `B1`, category: `business` },
  { word: `customer`, turkish: `müşteri`, imagePrompt: `A person in a shop selecting items from a shelf and placing them in a shopping basket`, level: `B1`, category: `business` },
  { word: `profit`, turkish: `kar`, imagePrompt: `An upward trending graph with the final bar much higher than the first, showing business growth`, level: `B1`, category: `business` },
  { word: `deadline`, turkish: `son tarih`, imagePrompt: `A calendar with a date circled in red and a clock ticking down next to a stack of papers`, level: `B1`, category: `business` },
  { word: `invoice`, turkish: `fatura`, imagePrompt: `A printed document listing goods or services provided with prices and a total amount due`, level: `B1`, category: `business` },
  { word: `colleague`, turkish: `iş arkadaşı`, imagePrompt: `Two coworkers at adjacent desks collaborating on a shared document on their screens`, level: `B1`, category: `business` },
  { word: `medicine`, turkish: `ilaç`, imagePrompt: `A row of orange prescription bottles with labels on a pharmacy shelf`, level: `B1`, category: `health` },
  { word: `vaccine`, turkish: `aşı`, imagePrompt: `A doctor drawing liquid into a syringe next to a small glass vial labeled for immunisation`, level: `B1`, category: `health` },
  { word: `surgery`, turkish: `ameliyat`, imagePrompt: `Surgeons in sterile gowns and masks bent over a patient under bright operating theatre lights`, level: `B1`, category: `health` },
  { word: `fever`, turkish: `ateş`, imagePrompt: `A person lying in bed with a flushed face, a thermometer in their mouth and a cold cloth on their forehead`, level: `B1`, category: `health` },
  { word: `bandage`, turkish: `bandaj`, imagePrompt: `A white gauze wrap wound firmly around an injured arm or leg to protect a wound`, level: `B1`, category: `health` },
  { word: `exercise`, turkish: `egzersiz`, imagePrompt: `A person at a gym lifting weights or running on a treadmill in workout clothing`, level: `B1`, category: `health` },
  { word: `nutrition`, turkish: `beslenme`, imagePrompt: `A colourful plate divided into portions of protein, vegetables, grains, and fruit`, level: `B1`, category: `health` },
  { word: `allergy`, turkish: `alerji`, imagePrompt: `A person sneezing near flowers with watery eyes and a red irritated nose reaction`, level: `B1`, category: `health` },
  { word: `dentist`, turkish: `diş hekimi`, imagePrompt: `A person in a dental chair with a bright light overhead while a dentist examines their teeth`, level: `B1`, category: `health` },
  { word: `university`, turkish: `üniversite`, imagePrompt: `A grand campus with stone buildings, archways, libraries and students walking between classes`, level: `B1`, category: `education` },
  { word: `degree`, turkish: `derece/diploma`, imagePrompt: `A rolled parchment tied with a ribbon handed to a graduate in a black cap and gown`, level: `B1`, category: `education` },
  { word: `research`, turkish: `araştırma`, imagePrompt: `A scientist in a lab coat surrounded by books and equipment collecting data on a clipboard`, level: `B1`, category: `education` },
  { word: `experiment`, turkish: `deney`, imagePrompt: `Test tubes, Bunsen burners, and coloured liquids in a science laboratory`, level: `B1`, category: `education` },
  { word: `theory`, turkish: `teori`, imagePrompt: `A physicist at a blackboard covered in complex equations and diagrams explaining a concept`, level: `B1`, category: `education` },
  { word: `evidence`, turkish: `kanıt`, imagePrompt: `Photographs, documents, and fingerprint samples laid out on an examination table`, level: `B1`, category: `education` },
  { word: `argument`, turkish: `argüman`, imagePrompt: `Two debaters at opposite podiums in a formal hall presenting opposing points of view`, level: `B1`, category: `education` },
  { word: `conclusion`, turkish: `sonuç`, imagePrompt: `The final paragraph of a report circled, summarising all the key points discussed above`, level: `B1`, category: `education` },
  { word: `scholarship`, turkish: `burs`, imagePrompt: `A student holding a letter of award for financial support to attend a prestigious university`, level: `B1`, category: `education` },
  { word: `assignment`, turkish: `ödev/görev`, imagePrompt: `A student at a desk surrounded by textbooks working late under a lamp on a written task`, level: `B1`, category: `education` },
  { word: `brilliant`, turkish: `parlak/zeki`, imagePrompt: `A student smiling as they see a perfect score on their returned exam paper`, level: `B1`, category: `adjectives` },
  { word: `curious`, turkish: `meraklı`, imagePrompt: `A child peering through a magnifying glass at a beetle on a leaf with intense interest`, level: `B1`, category: `adjectives` },
  { word: `generous`, turkish: `cömert`, imagePrompt: `A person giving a large wrapped gift to someone else with a warm open smile`, level: `B1`, category: `adjectives` },
  { word: `patient`, turkish: `sabırlı`, imagePrompt: `A person sitting calmly in a long queue, not fidgeting, reading a book peacefully`, level: `B1`, category: `adjectives` },
  { word: `flexible`, turkish: `esnek`, imagePrompt: `A gymnast bending her body into an impressive arch, showing great physical agility`, level: `B1`, category: `adjectives` },
  { word: `ambitious`, turkish: `hırslı`, imagePrompt: `A determined young professional climbing the rungs of a ladder with eyes fixed upward`, level: `B1`, category: `adjectives` },
  { word: `reliable`, turkish: `güvenilir`, imagePrompt: `A person always arriving on time, meeting every commitment with consistency and dependability`, level: `B1`, category: `adjectives` },
  { word: `efficient`, turkish: `verimli`, imagePrompt: `A worker completing tasks in record time with minimal wasted effort at a tidy desk`, level: `B1`, category: `adjectives` },
  { word: `creative`, turkish: `yaratıcı`, imagePrompt: `An artist surrounded by colourful paints, sketches, and half-built sculptures in a messy studio`, level: `B1`, category: `adjectives` },
  { word: `peaceful`, turkish: `huzurlu`, imagePrompt: `A person sitting by a still lake at dawn, everything quiet and perfectly serene`, level: `B1`, category: `adjectives` },
  { word: `democracy`, turkish: `demokrasi`, imagePrompt: `Citizens queuing outside a polling station to cast their vote in a free and fair election`, level: `B2`, category: `society` },
  { word: `justice`, turkish: `adalet`, imagePrompt: `The scales of justice perfectly balanced with eyes blindfolded holding a sword and scales`, level: `B2`, category: `society` },
  { word: `freedom`, turkish: `özgürlük`, imagePrompt: `An open birdcage door with a bird flying out into a bright open sky above the city`, level: `B2`, category: `society` },
  { word: `equality`, turkish: `eşitlik`, imagePrompt: `Two people of different backgrounds standing side by side at the same level with equal signs`, level: `B2`, category: `society` },
  { word: `diversity`, turkish: `çeşitlilik`, imagePrompt: `A circle of people of different ages, ethnicities and backgrounds holding hands together`, level: `B2`, category: `society` },
  { word: `poverty`, turkish: `yoksulluk`, imagePrompt: `A contrast of a crumbling neighbourhood next to a gleaming modern skyline in the same city`, level: `B2`, category: `society` },
  { word: `corruption`, turkish: `yolsuzluk`, imagePrompt: `A briefcase of cash being exchanged secretly under a table between two suited figures`, level: `B2`, category: `society` },
  { word: `revolution`, turkish: `devrim`, imagePrompt: `Crowds gathering in a central plaza with banners raised demanding fundamental political change`, level: `B2`, category: `society` },
  { word: `propaganda`, turkish: `propaganda`, imagePrompt: `Oversized posters with bold slogans covering a public building designed to influence opinion`, level: `B2`, category: `society` },
  { word: `prejudice`, turkish: `önyargı`, imagePrompt: `A person turning away from someone different without giving them a chance to speak`, level: `B2`, category: `society` },
  { word: `negotiate`, turkish: `müzakere etmek`, imagePrompt: `Two business executives at a table exchanging documents and reaching out to shake hands`, level: `B2`, category: `professional` },
  { word: `implement`, turkish: `uygulamak`, imagePrompt: `A project team executing steps from a detailed plan on a whiteboard with progress ticks`, level: `B2`, category: `professional` },
  { word: `evaluate`, turkish: `değerlendirmek`, imagePrompt: `An assessor reviewing a completed project with a scoring rubric and marking criteria`, level: `B2`, category: `professional` },
  { word: `collaborate`, turkish: `iş birliği yapmak`, imagePrompt: `Team members gathered around a table combining their individual contributions into one plan`, level: `B2`, category: `professional` },
  { word: `innovate`, turkish: `yenilik yapmak`, imagePrompt: `An engineer sketching a groundbreaking prototype design on a whiteboard in a tech lab`, level: `B2`, category: `professional` },
  { word: `delegate`, turkish: `devretmek`, imagePrompt: `A manager handing a folder of tasks to a team member, trusting them with responsibility`, level: `B2`, category: `professional` },
  { word: `strategy`, turkish: `strateji`, imagePrompt: `Chess pieces arranged on a board representing the calculated long-term plan of a player`, level: `B2`, category: `professional` },
  { word: `portfolio`, turkish: `portföy`, imagePrompt: `A designer presenting a bound collection of their best creative work at an interview`, level: `B2`, category: `professional` },
  { word: `milestone`, turkish: `kilometre taşı`, imagePrompt: `A project timeline with a starred checkpoint marking a major achievement reached`, level: `B2`, category: `professional` },
  { word: `disruption`, turkish: `aksaklık/bozucu değişim`, imagePrompt: `An established industry being upended by a newcomer with a completely different approach`, level: `B2`, category: `professional` },
  { word: `ecosystem`, turkish: `ekosistem`, imagePrompt: `A detailed diagram showing the complex web of connections between plants, animals and environment`, level: `B2`, category: `environment` },
  { word: `biodiversity`, turkish: `biyoçeşitlilik`, imagePrompt: `A rainforest teeming with colourful birds, insects, mammals and exotic plant life`, level: `B2`, category: `environment` },
  { word: `sustainability`, turkish: `sürdürülebilirlik`, imagePrompt: `Solar panels on rooftops, wind turbines and electric cars on a green energy-efficient city`, level: `B2`, category: `environment` },
  { word: `pollution`, turkish: `kirlilik`, imagePrompt: `Grey smog hanging over a city skyline with factory chimneys belching black smoke`, level: `B2`, category: `environment` },
  { word: `recycling`, turkish: `geri dönüşüm`, imagePrompt: `Colour-coded bins for glass, paper and plastic with sorted materials piled neatly beside them`, level: `B2`, category: `environment` },
  { word: `deforestation`, turkish: `ormansızlaşma`, imagePrompt: `A forest half cleared with stumps and bare earth showing where dense trees once stood`, level: `B2`, category: `environment` },
  { word: `erosion`, turkish: `erozyon`, imagePrompt: `Rainwater carving deep channels into exposed brown soil on a hillside losing its topsoil`, level: `B2`, category: `environment` },
  { word: `habitat`, turkish: `yaşam alanı`, imagePrompt: `A natural environment perfectly suited to a species, like wetlands for wading birds`, level: `B2`, category: `environment` },
  { word: `emission`, turkish: `emisyon`, imagePrompt: `A car exhaust releasing a cloud of carbon dioxide measured by a monitoring device`, level: `B2`, category: `environment` },
  { word: `conservation`, turkish: `koruma/muhafaza`, imagePrompt: `A ranger monitoring endangered animals in a protected nature reserve with binoculars`, level: `B2`, category: `environment` },
  { word: `sophisticated`, turkish: `sofistike/karmaşık`, imagePrompt: `An elegantly designed interior with precise details showing refined taste and complexity`, level: `B2`, category: `adjectives` },
  { word: `controversial`, turkish: `tartışmalı`, imagePrompt: `A town meeting erupting into heated debate with people on both sides raising their hands`, level: `B2`, category: `adjectives` },
  { word: `vulnerable`, turkish: `savunmasız`, imagePrompt: `A small creature exposed in an open space with no shelter or protection nearby`, level: `B2`, category: `adjectives` },
  { word: `transparent`, turkish: `şeffaf`, imagePrompt: `A glass-walled office where everything inside is fully visible to everyone passing outside`, level: `B2`, category: `adjectives` },
  { word: `inevitable`, turkish: `kaçınılmaz`, imagePrompt: `A ticking clock next to an event that is clearly about to happen with no way to prevent it`, level: `B2`, category: `adjectives` },
  { word: `sustainable`, turkish: `sürdürülebilir`, imagePrompt: `Energy sources and systems designed to last indefinitely without depleting natural resources`, level: `B2`, category: `adjectives` },
  { word: `overwhelming`, turkish: `ezici/bunaltıcı`, imagePrompt: `A person buried under a towering pile of work files with a look of complete overload`, level: `B2`, category: `adjectives` },
  { word: `comprehensive`, turkish: `kapsamlı`, imagePrompt: `A thick manual covering every single aspect of a topic from beginning to advanced level`, level: `B2`, category: `adjectives` },
  { word: `ambiguous`, turkish: `belirsiz/muğlak`, imagePrompt: `A sentence that could be understood in two completely different and contradictory ways`, level: `C1`, category: `academic` },
  { word: `empirical`, turkish: `ampirik`, imagePrompt: `Scientists collecting data through direct observation and controlled experiments in the field`, level: `C1`, category: `academic` },
  { word: `hypothesis`, turkish: `hipotez`, imagePrompt: `A researcher writing a testable prediction on a whiteboard before beginning an experiment`, level: `C1`, category: `academic` },
  { word: `methodology`, turkish: `metodoloji`, imagePrompt: `A detailed research plan outlining the exact steps and tools to be used in a study`, level: `C1`, category: `academic` },
  { word: `phenomenon`, turkish: `fenomen`, imagePrompt: `An extraordinary natural event that scientists observe, document and seek to explain`, level: `C1`, category: `academic` },
  { word: `paradigm`, turkish: `paradigma`, imagePrompt: `An old world map beside a modern one showing how fundamentally the entire framework shifted`, level: `C1`, category: `academic` },
  { word: `inference`, turkish: `çıkarım`, imagePrompt: `A detective examining clues and drawing a logical conclusion from indirect evidence`, level: `C1`, category: `academic` },
  { word: `correlation`, turkish: `korelasyon`, imagePrompt: `A scatter plot showing two variables moving together in the same direction over time`, level: `C1`, category: `academic` },
  { word: `implication`, turkish: `çıkarım/anlam`, imagePrompt: `A diagram showing how one event leads to a chain of indirect but significant consequences`, level: `C1`, category: `academic` },
  { word: `synthesis`, turkish: `sentez`, imagePrompt: `A researcher combining findings from many separate sources into one unified framework`, level: `C1`, category: `academic` },
  { word: `autonomy`, turkish: `özerklik`, imagePrompt: `A person confidently making their own independent decisions without needing others' approval`, level: `C1`, category: `abstract` },
  { word: `cognition`, turkish: `biliş`, imagePrompt: `A diagram of the human brain with highlighted regions representing thought and memory processes`, level: `C1`, category: `abstract` },
  { word: `resilience`, turkish: `dayanıklılık`, imagePrompt: `A bent but unbroken tree standing tall after a powerful storm has passed through`, level: `C1`, category: `abstract` },
  { word: `skepticism`, turkish: `şüphecilik`, imagePrompt: `A person raising an eyebrow and questioning a claim before accepting any evidence at face value`, level: `C1`, category: `abstract` },
  { word: `integrity`, turkish: `dürüstlük/bütünlük`, imagePrompt: `A person refusing a bribe and walking away from an envelope of money on a desk`, level: `C1`, category: `abstract` },
  { word: `rhetoric`, turkish: `retorik`, imagePrompt: `A powerful orator at a podium using language and gesture to persuade a large audience`, level: `C1`, category: `abstract` },
  { word: `pragmatic`, turkish: `pragmatik/pratik`, imagePrompt: `A problem-solver choosing the simplest workable solution rather than the most idealistic one`, level: `C1`, category: `abstract` },
  { word: `subjective`, turkish: `öznel`, imagePrompt: `Two people looking at the same abstract painting and expressing completely different reactions`, level: `C1`, category: `abstract` },
  { word: `ideology`, turkish: `ideoloji`, imagePrompt: `A political map with colour-coded regions each representing a different system of belief`, level: `C1`, category: `abstract` },
  { word: `perception`, turkish: `algı`, imagePrompt: `An optical illusion that can be seen as either a young woman or an old one depending on viewpoint`, level: `C1`, category: `abstract` },
  { word: `scrutinize`, turkish: `incelemek/denetlemek`, imagePrompt: `An auditor with a magnifying glass examining every line of a financial report on a desk`, level: `C1`, category: `verbs` },
  { word: `contemplate`, turkish: `düşünmek/tefekkür etmek`, imagePrompt: `A philosopher sitting alone in a quiet room staring at the horizon in deep reflective thought`, level: `C1`, category: `verbs` },
  { word: `articulate`, turkish: `açıkça ifade etmek`, imagePrompt: `A speaker carefully choosing precise words to explain a complex idea in perfectly clear terms`, level: `C1`, category: `verbs` },
  { word: `undermine`, turkish: `zayıflatmak`, imagePrompt: `A structure with its foundations slowly being eroded causing the whole building to tilt dangerously`, level: `C1`, category: `verbs` },
  { word: `facilitate`, turkish: `kolaylaştırmak`, imagePrompt: `A workshop leader helping two groups communicate better and find a shared working solution`, level: `C1`, category: `verbs` },
  { word: `acknowledge`, turkish: `kabul etmek/tanımak`, imagePrompt: `A person nodding and accepting that the other person's point of view has real merit`, level: `C1`, category: `verbs` },
  { word: `distinguish`, turkish: `ayırt etmek`, imagePrompt: `Two nearly identical objects side by side with an expert pointing to the subtle difference`, level: `C1`, category: `verbs` },
  { word: `anticipate`, turkish: `öngörmek`, imagePrompt: `A chess player already looking several moves ahead, planning for every possible opponent response`, level: `C1`, category: `verbs` },
  { word: `jeopardize`, turkish: `tehlikeye atmak`, imagePrompt: `A person making a reckless decision that puts a carefully built successful project at serious risk`, level: `C1`, category: `verbs` },
  { word: `reconcile`, turkish: `uzlaştırmak/bağdaştırmak`, imagePrompt: `Two people who disagreed sitting back down together and finding common ground to move forward`, level: `C1`, category: `verbs` },
  { word: `ubiquitous`, turkish: `her yerde mevcut`, imagePrompt: `The same brand logo appearing simultaneously on phones, billboards, laptops, cups and clothing everywhere`, level: `C2`, category: `advanced` },
  { word: `ephemeral`, turkish: `geçici/kısa ömürlü`, imagePrompt: `A soap bubble floating in the air for a brief moment before silently vanishing without a trace`, level: `C2`, category: `advanced` },
  { word: `serendipity`, turkish: `şans eseri buluş`, imagePrompt: `A scientist accidentally spilling a chemical and discovering an entirely new compound by chance`, level: `C2`, category: `advanced` },
  { word: `juxtaposition`, turkish: `yan yana koyma/karşıtlık`, imagePrompt: `A photograph showing a luxury penthouse directly above a cramped slum in the same city block`, level: `C2`, category: `advanced` },
  { word: `zeitgeist`, turkish: `devrin ruhu`, imagePrompt: `A collage of news headlines, fashion trends and viral moments that define a particular decade`, level: `C2`, category: `advanced` },
  { word: `quintessential`, turkish: `en tipik örnek`, imagePrompt: `An image so perfectly representing its category that it could serve as the textbook definition`, level: `C2`, category: `advanced` },
  { word: `melancholy`, turkish: `melankolik hüzün`, imagePrompt: `A person sitting by a rain-streaked window watching leaves fall with a wistful faraway look`, level: `C2`, category: `advanced` },
  { word: `eloquent`, turkish: `akıcı/güzel konuşan`, imagePrompt: `A speaker holding an audience completely spellbound with beautifully chosen and perfectly delivered words`, level: `C2`, category: `advanced` },
  { word: `ambivalence`, turkish: `çelişkili duygular`, imagePrompt: `A person standing at a crossroads unable to move left or right, pulled equally by both options`, level: `C2`, category: `advanced` },
  { word: `idiosyncratic`, turkish: `kendine özgü/alışılmadık`, imagePrompt: `An artist whose completely unique style is instantly recognisable and unlike anything else`, level: `C2`, category: `advanced` },
  { word: `vicarious`, turkish: `dolaylı/başkasının yerine`, imagePrompt: `A person feeling the thrill of adventure purely through watching someone else's extreme sport footage`, level: `C2`, category: `advanced` },
  { word: `nuance`, turkish: `nüans/ince fark`, imagePrompt: `A trained ear hearing the subtle tonal difference between two nearly identical musical notes`, level: `C2`, category: `advanced` },
  { word: `paradox`, turkish: `paradoks`, imagePrompt: `A sign on a door saying 'This sentence is false' creating an endless loop of contradiction`, level: `C2`, category: `advanced` },
  { word: `pragmatism`, turkish: `pragmatizm`, imagePrompt: `A builder choosing materials based purely on what works best rather than what looks impressive`, level: `C2`, category: `advanced` },
  { word: `contemplative`, turkish: `düşünceli/tefekkürsel`, imagePrompt: `A monk sitting motionless in a stone garden at dawn in a state of deep inward meditation`, level: `C2`, category: `advanced` },
  { word: `tournament`, turkish: `turnuva`, imagePrompt: `A bracket chart on a wall showing paired teams competing through rounds toward a final match`, level: `B1`, category: `sports` },
  { word: `championship`, turkish: `şampiyonluk`, imagePrompt: `An athlete standing on a podium holding a gleaming trophy above their head in triumph`, level: `B1`, category: `sports` },
  { word: `referee`, turkish: `hakem`, imagePrompt: `An official in a striped shirt blowing a whistle and showing a yellow card during a football match`, level: `B1`, category: `sports` },
  { word: `stadium`, turkish: `stadyum`, imagePrompt: `A massive oval arena packed with thousands of cheering fans watching a sporting event`, level: `B1`, category: `sports` },
  { word: `marathon`, turkish: `maraton`, imagePrompt: `Hundreds of runners in numbered bibs starting a 42-kilometre road race through a city`, level: `B1`, category: `sports` },
  { word: `medal`, turkish: `madalya`, imagePrompt: `A round metal disc on a ribbon hung around an athlete's neck to recognise their achievement`, level: `B1`, category: `sports` },
  { word: `trophy`, turkish: `kupa`, imagePrompt: `A tall silver or gold cup awarded to the winner of a competition displayed proudly on a shelf`, level: `B1`, category: `sports` },
  { word: `gallery`, turkish: `galeri`, imagePrompt: `White walls displaying large framed artworks in a quiet modern museum with a polished floor`, level: `A2`, category: `culture` },
  { word: `sculpture`, turkish: `heykel`, imagePrompt: `A three-dimensional carved stone or bronze figure displayed on a pedestal in a public square`, level: `B1`, category: `culture` },
  { word: `orchestra`, turkish: `orkestra`, imagePrompt: `Dozens of musicians in formal attire playing different instruments together on a concert stage`, level: `B1`, category: `culture` },
  { word: `theatre`, turkish: `tiyatro`, imagePrompt: `A velvet-curtained stage with actors performing under spotlights to a seated audience`, level: `A2`, category: `culture` },
  { word: `festival`, turkish: `festival`, imagePrompt: `Colourful outdoor stages, crowds of people, food stalls and live music at a summer celebration`, level: `A2`, category: `culture` },
  { word: `tradition`, turkish: `gelenek`, imagePrompt: `Families gathered in the same way they have for generations to celebrate a cultural custom`, level: `B1`, category: `culture` },
  { word: `heritage`, turkish: `miras`, imagePrompt: `Ancient stone ruins preserved as a landmark connecting the present to thousands of years of history`, level: `B1`, category: `culture` },
  { word: `passport`, turkish: `pasaport`, imagePrompt: `A small booklet with a photo and personal details shown at an international border crossing`, level: `A2`, category: `travel` },
  { word: `luggage`, turkish: `bagaj`, imagePrompt: `A large suitcase on wheels with a handle, stacked at an airport check-in desk`, level: `A2`, category: `travel` },
  { word: `visa`, turkish: `vize`, imagePrompt: `A stamped page in a passport granting official permission to enter a foreign country`, level: `A2`, category: `travel` },
  { word: `destination`, turkish: `varış noktası`, imagePrompt: `A map with a pin placed on the final location at the end of a planned travel route`, level: `A2`, category: `travel` },
  { word: `souvenir`, turkish: `hediyelik eşya`, imagePrompt: `A small decorative item bought in a tourist shop to remember a place visited abroad`, level: `A2`, category: `travel` },
  { word: `diagnosis`, turkish: `teşhis`, imagePrompt: `A doctor reviewing test results and scan images to determine what illness a patient has`, level: `B2`, category: `health` },
  { word: `symptom`, turkish: `belirti`, imagePrompt: `A patient describing a fever, cough and fatigue to a doctor who takes careful notes`, level: `B2`, category: `health` },
  { word: `pandemic`, turkish: `pandemi`, imagePrompt: `A world map with red zones spreading across continents showing a global health crisis`, level: `B2`, category: `health` },
  { word: `chromosome`, turkish: `kromozom`, imagePrompt: `A magnified image under a microscope showing paired DNA strands coiled into X-shaped structures`, level: `B2`, category: `science` },
  { word: `gravity`, turkish: `yerçekimi`, imagePrompt: `An apple falling from a tree branch toward the ground illustrating the force pulling objects down`, level: `B2`, category: `science` },
  { word: `molecule`, turkish: `molekül`, imagePrompt: `A 3D model of atoms bonded together forming the smallest unit of a chemical compound`, level: `B2`, category: `science` },
  { word: `atmosphere`, turkish: `atmosfer`, imagePrompt: `Layers of blue gas surrounding the Earth seen from space protecting the planet from radiation`, level: `B2`, category: `science` },
  { word: `evolution`, turkish: `evrim`, imagePrompt: `A sequence of figures from a simple four-legged creature progressively transforming into an upright human`, level: `B2`, category: `science` },
  { word: `loan`, turkish: `kredi/borç`, imagePrompt: `A person signing paperwork at a bank desk to borrow a sum of money to be repaid with interest`, level: `B1`, category: `finance` },
  { word: `interest`, turkish: `faiz/ilgi`, imagePrompt: `A percentage rate printed on a bank statement showing how much extra is owed on borrowed money`, level: `B1`, category: `finance` },
  { word: `investment`, turkish: `yatırım`, imagePrompt: `A graph showing money placed into stocks or property growing in value over time`, level: `B1`, category: `finance` },
  { word: `savings`, turkish: `tasarruf`, imagePrompt: `A piggy bank being filled coin by coin to build up a reserve of money for the future`, level: `B1`, category: `finance` },
  { word: `currency`, turkish: `döviz/para birimi`, imagePrompt: `A collection of banknotes from different countries spread out on a table`, level: `B1`, category: `finance` },
  { word: `tax`, turkish: `vergi`, imagePrompt: `A government form listing income and deductions used to calculate money owed to the state`, level: `B1`, category: `finance` },
  { word: `economy`, turkish: `ekonomi`, imagePrompt: `A large circular diagram showing the flow of money between consumers, businesses and government`, level: `B1`, category: `finance` },
  { word: `pencil`, turkish: `kalem`, imagePrompt: `A wooden stick with a graphite core sharpened to a point used to draw or write on paper`, level: `A1`, category: `stationery` },
  { word: `paper`, turkish: `kağıt`, imagePrompt: `A flat white sheet used for writing, drawing or printing, stacked neatly on a desk`, level: `A1`, category: `stationery` },
  { word: `phone`, turkish: `telefon`, imagePrompt: `A rectangular touchscreen device held in the hand used to call, text and browse the internet`, level: `A1`, category: `technology` },
  { word: `television`, turkish: `televizyon`, imagePrompt: `A flat screen on a wall displaying moving images and sound for home entertainment`, level: `A1`, category: `household` },
  { word: `music`, turkish: `müzik`, imagePrompt: `Musical notes floating from a piano with vibrations in the air felt by a listening crowd`, level: `A1`, category: `culture` },
  { word: `photo`, turkish: `fotoğraf`, imagePrompt: `A printed or digital image capturing a frozen moment in time from a camera`, level: `A1`, category: `culture` },
  { word: `letter`, turkish: `mektup/harf`, imagePrompt: `A handwritten note on folded paper placed inside an envelope addressed and stamped for mailing`, level: `A1`, category: `communication` },
  { word: `map`, turkish: `harita`, imagePrompt: `A flat representation of a geographic area with roads, rivers and landmarks drawn on it`, level: `A1`, category: `travel` },
  { word: `money`, turkish: `para`, imagePrompt: `A collection of paper notes and metal coins of various denominations stacked on a surface`, level: `A1`, category: `finance` },
  { word: `ticket`, turkish: `bilet`, imagePrompt: `A small printed card granting access to a concert, film, bus or sports event when shown at the entrance`, level: `A1`, category: `travel` }
] as const;
